// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System.Runtime.InteropServices;
using System.Text;

namespace TarantoolWorld.wit.imports.tarantool.tarantool
{
    public static class ErrorInterop {

        internal static class NewWasmInterop
        {
            [DllImport("tarantool:tarantool/error", EntryPoint = "new"), WasmImportLinkage]
            internal static extern void wasmImportNew(nint p0, int p1, nint p2, int p3, int p4, nint p5);
        }

        public  static unsafe global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError New(string message, string type, uint code)
        {
            var cleanups = new List<Action>();

            var utf8Bytes = Encoding.UTF8.GetBytes(message);
            var length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            var interopString = gcHandle.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle.Free());

            var utf8Bytes1 = Encoding.UTF8.GetBytes(type);
            var length2 = utf8Bytes1.Length;
            var gcHandle3 = GCHandle.Alloc(utf8Bytes1, GCHandleType.Pinned);
            var interopString0 = gcHandle3.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle3.Free());

            var retArea = stackalloc uint[13+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            NewWasmInterop.wasmImportNew(interopString.ToInt32(), length, interopString0.ToInt32(), length2, unchecked((int)(code)), ptr);

            List<(string, string)>? lifted;

            switch (new Span<byte>((void*)(ptr + 20), 1)[0]) {
                case 0: {
                    lifted = null;
                    break;
                }

                case 1: {

                    var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)));
                    for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)); ++index) {
                        nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)) + (index * 16);

                        array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                    }

                    lifted = array;
                    break;
                }

                default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 20), 1)[0]));
            }

            string? lifted12;

            switch (new Span<byte>((void*)(ptr + 32), 1)[0]) {
                case 0: {
                    lifted12 = null;
                    break;
                }

                case 1: {

                    lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)));
                    break;
                }

                default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 32), 1)[0]));
            }

            uint? lifted17;

            switch (new Span<byte>((void*)(ptr + 44), 1)[0]) {
                case 0: {
                    lifted17 = null;
                    break;
                }

                case 1: {

                    lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4))));
                    break;
                }

                default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 44), 1)[0]));
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            return new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
            Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)))), lifted, lifted12, lifted17);

        }

        internal static class SetWasmInterop
        {
            [DllImport("tarantool:tarantool/error", EntryPoint = "set"), WasmImportLinkage]
            internal static extern void wasmImportSet(nint p0, int p1, nint p2, int p3, int p4, int p5, nint p6, int p7, int p8, nint p9, int p10, int p11, int p12);
        }

        public  static unsafe void Set(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError err)
        {
            var cleanups = new List<Action>();

            var utf8Bytes = Encoding.UTF8.GetBytes(err.message);
            var length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            var interopString = gcHandle.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle.Free());

            var utf8Bytes1 = Encoding.UTF8.GetBytes(err.type);
            var length2 = utf8Bytes1.Length;
            var gcHandle3 = GCHandle.Alloc(utf8Bytes1, GCHandleType.Pinned);
            var interopString0 = gcHandle3.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle3.Free());

            int lowered;
            nint lowered17;
            int lowered18;

            if (err.payload != null) {
                var payload6 = (List<(string, string)>) err.payload;

                void* address;
                if ((16 * payload6.Count) < 1024) {
                    var retArea = stackalloc uint[(4*payload6.Count)+1];
                    address = (void*)(((int)retArea) + (4 - 1) & -4);
                }
                else
                {
                    var bufferSize = 16 * (nuint)payload6.Count;
                    address = NativeMemory.AlignedAlloc(bufferSize, 4);
                    cleanups.Add(()=> NativeMemory.AlignedFree(address));
                }

                for (int index = 0; index < payload6.Count; ++index) {
                    (string, string) element7 = payload6[index];
                    int basePtr8 = (int)address + (index * 16);

                    var utf8Bytes10 = Encoding.UTF8.GetBytes(element7.Item1);
                    var length11 = utf8Bytes10.Length;
                    var gcHandle12 = GCHandle.Alloc(utf8Bytes10, GCHandleType.Pinned);
                    var interopString9 = gcHandle12.AddrOfPinnedObject();

                    cleanups.Add(()=> gcHandle12.Free());
                    BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr8 + 4), 4), length11);
                    BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr8 + 0), 4), interopString9.ToInt32());

                    var utf8Bytes14 = Encoding.UTF8.GetBytes(element7.Item2);
                    var length15 = utf8Bytes14.Length;
                    var gcHandle16 = GCHandle.Alloc(utf8Bytes14, GCHandleType.Pinned);
                    var interopString13 = gcHandle16.AddrOfPinnedObject();

                    cleanups.Add(()=> gcHandle16.Free());
                    BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr8 + 12), 4), length15);
                    BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr8 + 8), 4), interopString13.ToInt32());

                }

                lowered = 1;
                lowered17 = (int)address;
                lowered18 = payload6.Count;

            } else {

                lowered = 0;
                lowered17 = 0;
                lowered18 = 0;

            }

            int lowered29;
            nint lowered30;
            int lowered31;

            if (err.file != null) {
                var payload24 = (string) err.file;

                var utf8Bytes26 = Encoding.UTF8.GetBytes(payload24);
                var length27 = utf8Bytes26.Length;
                var gcHandle28 = GCHandle.Alloc(utf8Bytes26, GCHandleType.Pinned);
                var interopString25 = gcHandle28.AddrOfPinnedObject();

                cleanups.Add(()=> gcHandle28.Free());

                lowered29 = 1;
                lowered30 = interopString25.ToInt32();
                lowered31 = length27;

            } else {

                lowered29 = 0;
                lowered30 = 0;
                lowered31 = 0;

            }

            int lowered38;
            int lowered39;

            if (err.line != null) {
                var payload37 = (uint) err.line;

                lowered38 = 1;
                lowered39 = unchecked((int)(payload37));

            } else {

                lowered38 = 0;
                lowered39 = 0;

            }
            SetWasmInterop.wasmImportSet(interopString.ToInt32(), length, interopString0.ToInt32(), length2, unchecked((int)(err.code)), lowered, lowered17, lowered18, lowered29, lowered30, lowered31, lowered38, lowered39);

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }

        }

        internal static class LastWasmInterop
        {
            [DllImport("tarantool:tarantool/error", EntryPoint = "last"), WasmImportLinkage]
            internal static extern void wasmImportLast(nint p0);
        }

        public  static unsafe global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError? Last()
        {

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            LastWasmInterop.wasmImportLast(ptr);

            global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError? lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {
                    lifted18 = null;
                    break;
                }

                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted18 = new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17);
                    break;
                }

                default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 0), 1)[0]));
            }
            return lifted18;

        }

        internal static class ClearWasmInterop
        {
            [DllImport("tarantool:tarantool/error", EntryPoint = "clear"), WasmImportLinkage]
            internal static extern void wasmImportClear();
        }

        public  static unsafe void Clear()
        {
            ClearWasmInterop.wasmImportClear();

        }

        internal static class ToStringWasmInterop
        {
            [DllImport("tarantool:tarantool/error", EntryPoint = "to-string"), WasmImportLinkage]
            internal static extern void wasmImportToString(nint p0, int p1, nint p2, int p3, int p4, int p5, nint p6, int p7, int p8, nint p9, int p10, int p11, int p12, nint p13);
        }

        public  static unsafe string ToString(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError err)
        {
            var cleanups = new List<Action>();

            var utf8Bytes = Encoding.UTF8.GetBytes(err.message);
            var length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            var interopString = gcHandle.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle.Free());

            var utf8Bytes1 = Encoding.UTF8.GetBytes(err.type);
            var length2 = utf8Bytes1.Length;
            var gcHandle3 = GCHandle.Alloc(utf8Bytes1, GCHandleType.Pinned);
            var interopString0 = gcHandle3.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle3.Free());

            int lowered;
            nint lowered17;
            int lowered18;

            if (err.payload != null) {
                var payload6 = (List<(string, string)>) err.payload;

                void* address;
                if ((16 * payload6.Count) < 1024) {
                    var retArea = stackalloc uint[(4*payload6.Count)+1];
                    address = (void*)(((int)retArea) + (4 - 1) & -4);
                }
                else
                {
                    var bufferSize = 16 * (nuint)payload6.Count;
                    address = NativeMemory.AlignedAlloc(bufferSize, 4);
                    cleanups.Add(()=> NativeMemory.AlignedFree(address));
                }

                for (int index = 0; index < payload6.Count; ++index) {
                    (string, string) element7 = payload6[index];
                    int basePtr8 = (int)address + (index * 16);

                    var utf8Bytes10 = Encoding.UTF8.GetBytes(element7.Item1);
                    var length11 = utf8Bytes10.Length;
                    var gcHandle12 = GCHandle.Alloc(utf8Bytes10, GCHandleType.Pinned);
                    var interopString9 = gcHandle12.AddrOfPinnedObject();

                    cleanups.Add(()=> gcHandle12.Free());
                    BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr8 + 4), 4), length11);
                    BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr8 + 0), 4), interopString9.ToInt32());

                    var utf8Bytes14 = Encoding.UTF8.GetBytes(element7.Item2);
                    var length15 = utf8Bytes14.Length;
                    var gcHandle16 = GCHandle.Alloc(utf8Bytes14, GCHandleType.Pinned);
                    var interopString13 = gcHandle16.AddrOfPinnedObject();

                    cleanups.Add(()=> gcHandle16.Free());
                    BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr8 + 12), 4), length15);
                    BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr8 + 8), 4), interopString13.ToInt32());

                }

                lowered = 1;
                lowered17 = (int)address;
                lowered18 = payload6.Count;

            } else {

                lowered = 0;
                lowered17 = 0;
                lowered18 = 0;

            }

            int lowered29;
            nint lowered30;
            int lowered31;

            if (err.file != null) {
                var payload24 = (string) err.file;

                var utf8Bytes26 = Encoding.UTF8.GetBytes(payload24);
                var length27 = utf8Bytes26.Length;
                var gcHandle28 = GCHandle.Alloc(utf8Bytes26, GCHandleType.Pinned);
                var interopString25 = gcHandle28.AddrOfPinnedObject();

                cleanups.Add(()=> gcHandle28.Free());

                lowered29 = 1;
                lowered30 = interopString25.ToInt32();
                lowered31 = length27;

            } else {

                lowered29 = 0;
                lowered30 = 0;
                lowered31 = 0;

            }

            int lowered38;
            int lowered39;

            if (err.line != null) {
                var payload37 = (uint) err.line;

                lowered38 = 1;
                lowered39 = unchecked((int)(payload37));

            } else {

                lowered38 = 0;
                lowered39 = 0;

            }

            var retArea40 = stackalloc uint[2+1];
            var ptr = ((int)retArea40) + (4 - 1) & -4;
            ToStringWasmInterop.wasmImportToString(interopString.ToInt32(), length, interopString0.ToInt32(), length2, unchecked((int)(err.code)), lowered, lowered17, lowered18, lowered29, lowered30, lowered31, lowered38, lowered39, ptr);

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            return Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)));

        }

    }
}
