// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System.Text;
using System.Runtime.InteropServices;

namespace TarantoolWorld.wit.imports.tarantool.tarantool
{
    public static class KeyDefInterop {

        internal static class NewWasmInterop
        {
            [DllImport("tarantool:tarantool/key-def", EntryPoint = "new"), WasmImportLinkage]
            internal static extern void wasmImportNew(nint p0, int p1, nint p2);
        }

        public  static unsafe ulong New(List<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.KeyPartDef> parts)
        {
            var cleanups = new List<Action>();

            void* address;
            if ((48 * parts.Count) < 1024) {
                var retArea = stackalloc uint[(12*parts.Count)+1];
                address = (void*)(((int)retArea) + (4 - 1) & -4);
            }
            else
            {
                var bufferSize = 48 * (nuint)parts.Count;
                address = NativeMemory.AlignedAlloc(bufferSize, 4);
                cleanups.Add(()=> NativeMemory.AlignedFree(address));
            }

            for (int index = 0; index < parts.Count; ++index) {
                global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.KeyPartDef element = parts[index];
                int basePtr = (int)address + (index * 48);

                switch (element.field.Tag) {
                    case 0: {
                        uint payload = element.field.AsNumber;
                        *(byte*)(basePtr + 0) = (byte)0;
                        BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr + 4), 4), unchecked((int)(payload)));

                        break;
                    }
                    case 1: {
                        string payload4 = element.field.AsName;
                        *(byte*)(basePtr + 0) = (byte)1;

                        var utf8Bytes = Encoding.UTF8.GetBytes(payload4);
                        var length = utf8Bytes.Length;
                        var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
                        var interopString = gcHandle.AddrOfPinnedObject();

                        cleanups.Add(()=> gcHandle.Free());
                        BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr + 8), 4), length);
                        BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr + 4), 4), interopString.ToInt32());

                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {element.field}");
                }

                var utf8Bytes6 = Encoding.UTF8.GetBytes(element.fieldType);
                var length7 = utf8Bytes6.Length;
                var gcHandle8 = GCHandle.Alloc(utf8Bytes6, GCHandleType.Pinned);
                var interopString5 = gcHandle8.AddrOfPinnedObject();

                cleanups.Add(()=> gcHandle8.Free());
                BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr + 16), 4), length7);
                BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr + 12), 4), interopString5.ToInt32());

                if (element.collation != null) {
                    var payload14 = (string) element.collation;
                    *(byte*)(basePtr + 20) = (byte)1;

                    var utf8Bytes16 = Encoding.UTF8.GetBytes(payload14);
                    var length17 = utf8Bytes16.Length;
                    var gcHandle18 = GCHandle.Alloc(utf8Bytes16, GCHandleType.Pinned);
                    var interopString15 = gcHandle18.AddrOfPinnedObject();

                    cleanups.Add(()=> gcHandle18.Free());
                    BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr + 28), 4), length17);
                    BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr + 24), 4), interopString15.ToInt32());

                } else {

                    *(byte*)(basePtr + 20) = (byte)0;

                }

                if (element.path != null) {
                    var payload24 = (string) element.path;
                    *(byte*)(basePtr + 32) = (byte)1;

                    var utf8Bytes26 = Encoding.UTF8.GetBytes(payload24);
                    var length27 = utf8Bytes26.Length;
                    var gcHandle28 = GCHandle.Alloc(utf8Bytes26, GCHandleType.Pinned);
                    var interopString25 = gcHandle28.AddrOfPinnedObject();

                    cleanups.Add(()=> gcHandle28.Free());
                    BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr + 40), 4), length27);
                    BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr + 36), 4), interopString25.ToInt32());

                } else {

                    *(byte*)(basePtr + 32) = (byte)0;

                }
                *(byte*)(basePtr + 44) = (byte)(int)element.flags;

            }

            var retArea29 = stackalloc ulong[8+1];
            var ptr = ((int)retArea29) + (8 - 1) & -8;
            NewWasmInterop.wasmImportNew((int)address, parts.Count, ptr);

            Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted51;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted51 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                            for (int index40 = 0; index40 < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index40) {
                                nint basePtr39 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index40 * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr39 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr39 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr39 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr39 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                    }

                    string? lifted45;

                    switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                        case 0: {
                            lifted45 = null;
                            break;
                        }

                        case 1: {

                            lifted45 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                    }

                    uint? lifted50;

                    switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                        case 0: {
                            lifted50 = null;
                            break;
                        }

                        case 1: {

                            lifted50 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                    }

                    lifted51 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted45, lifted50));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            if (lifted51.IsOk)
            {
                var tmp = lifted51.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted51.AsErr!, 0);
            }

        }

        internal static class MergeWasmInterop
        {
            [DllImport("tarantool:tarantool/key-def", EntryPoint = "merge"), WasmImportLinkage]
            internal static extern void wasmImportMerge(long p0, long p1, nint p2);
        }

        public  static unsafe ulong Merge(ulong left, ulong right)
        {

            var retArea = stackalloc ulong[8+1];
            var ptr = ((int)retArea) + (8 - 1) & -8;
            MergeWasmInterop.wasmImportMerge(unchecked((long)(left)), unchecked((long)(right)), ptr);

            Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                    }

                    lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        internal static class ValidateKeyWasmInterop
        {
            [DllImport("tarantool:tarantool/key-def", EntryPoint = "validate-key"), WasmImportLinkage]
            internal static extern void wasmImportValidateKey(long p0, nint p1, int p2, nint p3);
        }

        public  static unsafe (bool, uint) ValidateKey(ulong keyDef, byte[] key)
        {
            var cleanups = new List<Action>();

            var gcHandle = GCHandle.Alloc(key, GCHandleType.Pinned);
            var listPtr = gcHandle.AddrOfPinnedObject();
            cleanups.Add(()=> gcHandle.Free());

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            ValidateKeyWasmInterop.wasmImportValidateKey(unchecked((long)(keyDef)), (nint)listPtr, (key).Length, ptr);

            Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(((new Span<byte>((void*)(ptr + 4), 1)[0] != 0), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted18 = Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        public  static unsafe (bool, uint) ValidateKey(ulong keyDef, Span<byte> key)
        {
            fixed (void* listPtr = key)
            {

                var retArea = stackalloc uint[14+1];
                var ptr = ((int)retArea) + (4 - 1) & -4;
                ValidateKeyWasmInterop.wasmImportValidateKey(unchecked((long)(keyDef)), (nint)listPtr, (key).Length, ptr);

                Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted18 = Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(((new Span<byte>((void*)(ptr + 4), 1)[0] != 0), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))))));
                        break;
                    }
                    case 1: {

                        List<(string, string)>? lifted;

                        switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                            case 0: {
                                lifted = null;
                                break;
                            }

                            case 1: {

                                var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                                for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                    nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                    array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                                }

                                lifted = array;
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                        }

                        string? lifted12;

                        switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                            case 0: {
                                lifted12 = null;
                                break;
                            }

                            case 1: {

                                lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                        }

                        uint? lifted17;

                        switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                            case 0: {
                                lifted17 = null;
                                break;
                            }

                            case 1: {

                                lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                        }

                        lifted18 = Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                        Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted18.IsOk)
                {
                    var tmp = lifted18.AsOk;
                    return tmp;
                }
                else
                {
                    throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
                }
            }

        }

        public  static unsafe (bool, uint) ValidateKey(ulong keyDef, Memory<byte> key)
        {
            fixed (void* listPtr = key.Span)
            {

                var retArea = stackalloc uint[14+1];
                var ptr = ((int)retArea) + (4 - 1) & -4;
                ValidateKeyWasmInterop.wasmImportValidateKey(unchecked((long)(keyDef)), (nint)listPtr, (key).Length, ptr);

                Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted18 = Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(((new Span<byte>((void*)(ptr + 4), 1)[0] != 0), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))))));
                        break;
                    }
                    case 1: {

                        List<(string, string)>? lifted;

                        switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                            case 0: {
                                lifted = null;
                                break;
                            }

                            case 1: {

                                var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                                for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                    nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                    array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                                }

                                lifted = array;
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                        }

                        string? lifted12;

                        switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                            case 0: {
                                lifted12 = null;
                                break;
                            }

                            case 1: {

                                lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                        }

                        uint? lifted17;

                        switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                            case 0: {
                                lifted17 = null;
                                break;
                            }

                            case 1: {

                                lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                        }

                        lifted18 = Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                        Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted18.IsOk)
                {
                    var tmp = lifted18.AsOk;
                    return tmp;
                }
                else
                {
                    throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
                }
            }

        }

        internal static class ValidateFullKeyWasmInterop
        {
            [DllImport("tarantool:tarantool/key-def", EntryPoint = "validate-full-key"), WasmImportLinkage]
            internal static extern void wasmImportValidateFullKey(long p0, nint p1, int p2, nint p3);
        }

        public  static unsafe (bool, uint) ValidateFullKey(ulong keyDef, byte[] key)
        {
            var cleanups = new List<Action>();

            var gcHandle = GCHandle.Alloc(key, GCHandleType.Pinned);
            var listPtr = gcHandle.AddrOfPinnedObject();
            cleanups.Add(()=> gcHandle.Free());

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            ValidateFullKeyWasmInterop.wasmImportValidateFullKey(unchecked((long)(keyDef)), (nint)listPtr, (key).Length, ptr);

            Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(((new Span<byte>((void*)(ptr + 4), 1)[0] != 0), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted18 = Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        public  static unsafe (bool, uint) ValidateFullKey(ulong keyDef, Span<byte> key)
        {
            fixed (void* listPtr = key)
            {

                var retArea = stackalloc uint[14+1];
                var ptr = ((int)retArea) + (4 - 1) & -4;
                ValidateFullKeyWasmInterop.wasmImportValidateFullKey(unchecked((long)(keyDef)), (nint)listPtr, (key).Length, ptr);

                Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted18 = Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(((new Span<byte>((void*)(ptr + 4), 1)[0] != 0), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))))));
                        break;
                    }
                    case 1: {

                        List<(string, string)>? lifted;

                        switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                            case 0: {
                                lifted = null;
                                break;
                            }

                            case 1: {

                                var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                                for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                    nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                    array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                                }

                                lifted = array;
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                        }

                        string? lifted12;

                        switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                            case 0: {
                                lifted12 = null;
                                break;
                            }

                            case 1: {

                                lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                        }

                        uint? lifted17;

                        switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                            case 0: {
                                lifted17 = null;
                                break;
                            }

                            case 1: {

                                lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                        }

                        lifted18 = Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                        Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted18.IsOk)
                {
                    var tmp = lifted18.AsOk;
                    return tmp;
                }
                else
                {
                    throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
                }
            }

        }

        public  static unsafe (bool, uint) ValidateFullKey(ulong keyDef, Memory<byte> key)
        {
            fixed (void* listPtr = key.Span)
            {

                var retArea = stackalloc uint[14+1];
                var ptr = ((int)retArea) + (4 - 1) & -4;
                ValidateFullKeyWasmInterop.wasmImportValidateFullKey(unchecked((long)(keyDef)), (nint)listPtr, (key).Length, ptr);

                Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted18 = Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(((new Span<byte>((void*)(ptr + 4), 1)[0] != 0), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))))));
                        break;
                    }
                    case 1: {

                        List<(string, string)>? lifted;

                        switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                            case 0: {
                                lifted = null;
                                break;
                            }

                            case 1: {

                                var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                                for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                    nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                    array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                                }

                                lifted = array;
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                        }

                        string? lifted12;

                        switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                            case 0: {
                                lifted12 = null;
                                break;
                            }

                            case 1: {

                                lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                        }

                        uint? lifted17;

                        switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                            case 0: {
                                lifted17 = null;
                                break;
                            }

                            case 1: {

                                lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                        }

                        lifted18 = Result<(bool, uint), global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                        Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted18.IsOk)
                {
                    var tmp = lifted18.AsOk;
                    return tmp;
                }
                else
                {
                    throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
                }
            }

        }

        internal static class CompareWasmInterop
        {
            [DllImport("tarantool:tarantool/key-def", EntryPoint = "compare"), WasmImportLinkage]
            internal static extern int wasmImportCompare(long p0, long p1, long p2);
        }

        public  static unsafe int Compare(ulong keyDef, ulong left, ulong right)
        {
            var result =  CompareWasmInterop.wasmImportCompare(unchecked((long)(keyDef)), unchecked((long)(left)), unchecked((long)(right)));
            return result;

        }

        internal static class CompareKeysWasmInterop
        {
            [DllImport("tarantool:tarantool/key-def", EntryPoint = "compare-keys"), WasmImportLinkage]
            internal static extern int wasmImportCompareKeys(long p0, long p1, long p2);
        }

        public  static unsafe int CompareKeys(ulong keyDef, ulong left, ulong right)
        {
            var result =  CompareKeysWasmInterop.wasmImportCompareKeys(unchecked((long)(keyDef)), unchecked((long)(left)), unchecked((long)(right)));
            return result;

        }

        internal static class ExtractKeyWasmInterop
        {
            [DllImport("tarantool:tarantool/key-def", EntryPoint = "extract-key"), WasmImportLinkage]
            internal static extern long wasmImportExtractKey(long p0, long p1);
        }

        public  static unsafe ulong ExtractKey(ulong keyDef, ulong tuple)
        {
            var result =  ExtractKeyWasmInterop.wasmImportExtractKey(unchecked((long)(keyDef)), unchecked((long)(tuple)));
            return unchecked((ulong)(result));

        }

        internal static class PartCountWasmInterop
        {
            [DllImport("tarantool:tarantool/key-def", EntryPoint = "part-count"), WasmImportLinkage]
            internal static extern void wasmImportPartCount(long p0, nint p1);
        }

        public  static unsafe uint PartCount(ulong keyDef)
        {

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            PartCountWasmInterop.wasmImportPartCount(unchecked((long)(keyDef)), ptr);

            Result<uint, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<uint, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted18 = Result<uint, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        internal static class ValidateTupleWasmInterop
        {
            [DllImport("tarantool:tarantool/key-def", EntryPoint = "validate-tuple"), WasmImportLinkage]
            internal static extern int wasmImportValidateTuple(long p0, long p1);
        }

        public  static unsafe bool ValidateTuple(ulong keyDef, ulong tuple)
        {
            var result =  ValidateTupleWasmInterop.wasmImportValidateTuple(unchecked((long)(keyDef)), unchecked((long)(tuple)));
            return (result != 0);

        }

        internal static class DupWasmInterop
        {
            [DllImport("tarantool:tarantool/key-def", EntryPoint = "dup"), WasmImportLinkage]
            internal static extern void wasmImportDup(long p0, nint p1);
        }

        public  static unsafe ulong Dup(ulong keyDef)
        {

            var retArea = stackalloc ulong[8+1];
            var ptr = ((int)retArea) + (8 - 1) & -8;
            DupWasmInterop.wasmImportDup(unchecked((long)(keyDef)), ptr);

            Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                    }

                    lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        internal static class DeleteWasmInterop
        {
            [DllImport("tarantool:tarantool/key-def", EntryPoint = "delete"), WasmImportLinkage]
            internal static extern void wasmImportDelete(long p0);
        }

        public  static unsafe void Delete(ulong keyDef)
        {
            DeleteWasmInterop.wasmImportDelete(unchecked((long)(keyDef)));

        }

        internal static class DumpPartsWasmInterop
        {
            [DllImport("tarantool:tarantool/key-def", EntryPoint = "dump-parts"), WasmImportLinkage]
            internal static extern void wasmImportDumpParts(long p0, nint p1);
        }

        public  static unsafe List<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.KeyPartDef> DumpParts(ulong keyDef)
        {

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            DumpPartsWasmInterop.wasmImportDumpParts(unchecked((long)(keyDef)), ptr);

            Result<List<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.KeyPartDef>, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted37;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    var array = new List<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.KeyPartDef>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)));
                    for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)); ++index) {
                        nint basePtr1 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)) + (index * 48);

                        global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.FieldIdentifier lifted;

                        switch (new Span<byte>((void*)(basePtr1 + 0), 1)[0]) {
                            case 0: {

                                lifted = global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.FieldIdentifier.Number(unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(basePtr1 + 4), 4)))));
                                break;
                            }
                            case 1: {

                                lifted = global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.FieldIdentifier.Name(Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr1 + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr1 + 8), 4))));
                                break;
                            }

                            default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(basePtr1 + 0), 1)[0]}");
                        }

                        string? lifted10;

                        switch (new Span<byte>((void*)(basePtr1 + 20), 1)[0]) {
                            case 0: {
                                lifted10 = null;
                                break;
                            }

                            case 1: {

                                lifted10 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr1 + 24), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr1 + 28), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(basePtr1 + 20), 1)[0]));
                        }

                        string? lifted15;

                        switch (new Span<byte>((void*)(basePtr1 + 32), 1)[0]) {
                            case 0: {
                                lifted15 = null;
                                break;
                            }

                            case 1: {

                                lifted15 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr1 + 36), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr1 + 40), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(basePtr1 + 32), 1)[0]));
                        }

                        array.Add(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.KeyPartDef (
                        lifted, Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr1 + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr1 + 16), 4))), lifted10, lifted15, (global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.KeyPartFlags)(new Span<byte>((void*)(basePtr1 + 44), 1)[0])));
                    }

                    lifted37 = Result<List<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.KeyPartDef>, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(array);
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted26;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted26 = null;
                            break;
                        }

                        case 1: {

                            var array24 = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index25 = 0; index25 < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index25) {
                                nint basePtr23 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index25 * 16);

                                array24.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr23 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr23 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr23 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr23 + 12), 4)))));
                            }

                            lifted26 = array24;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted31;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted31 = null;
                            break;
                        }

                        case 1: {

                            lifted31 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted36;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted36 = null;
                            break;
                        }

                        case 1: {

                            lifted36 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted37 = Result<List<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.KeyPartDef>, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted26, lifted31, lifted36));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted37.IsOk)
            {
                var tmp = lifted37.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted37.AsErr!, 0);
            }

        }

    }
}
