// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System.Runtime.InteropServices;
using System.Text;

namespace TarantoolWorld.wit.imports.tarantool.tarantool
{
    public static class BoxInterop {

        internal static class SchemaVersionWasmInterop
        {
            [DllImport("tarantool:tarantool/box", EntryPoint = "schema-version"), WasmImportLinkage]
            internal static extern long wasmImportSchemaVersion();
        }

        public  static unsafe long SchemaVersion()
        {
            var result =  SchemaVersionWasmInterop.wasmImportSchemaVersion();
            return result;

        }

        internal static class SpaceByNameWasmInterop
        {
            [DllImport("tarantool:tarantool/box", EntryPoint = "space-by-name"), WasmImportLinkage]
            internal static extern void wasmImportSpaceByName(nint p0, int p1, nint p2);
        }

        public  static unsafe global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Space SpaceByName(string name)
        {
            var cleanups = new List<Action>();

            var utf8Bytes = Encoding.UTF8.GetBytes(name);
            var length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            var interopString = gcHandle.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle.Free());

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            SpaceByNameWasmInterop.wasmImportSpaceByName(interopString.ToInt32(), length, ptr);

            Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Space, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Space, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Space (
                    BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted18 = Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Space, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        internal static class IndexByNameWasmInterop
        {
            [DllImport("tarantool:tarantool/box", EntryPoint = "index-by-name"), WasmImportLinkage]
            internal static extern void wasmImportIndexByName(nint p0, int p1, int p2, nint p3);
        }

        public  static unsafe global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Index IndexByName(string name, int indexBase)
        {
            var cleanups = new List<Action>();

            var utf8Bytes = Encoding.UTF8.GetBytes(name);
            var length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            var interopString = gcHandle.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle.Free());

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            IndexByNameWasmInterop.wasmImportIndexByName(interopString.ToInt32(), length, indexBase, ptr);

            Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Index, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Index, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Index (
                    BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted18 = Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Index, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        internal static class InsertWasmInterop
        {
            [DllImport("tarantool:tarantool/box", EntryPoint = "insert"), WasmImportLinkage]
            internal static extern void wasmImportInsert(int p0, nint p1, int p2, nint p3);
        }

        public  static unsafe ulong Insert(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Space space, byte[] tup)
        {
            var cleanups = new List<Action>();

            var gcHandle = GCHandle.Alloc(tup, GCHandleType.Pinned);
            var listPtr = gcHandle.AddrOfPinnedObject();
            cleanups.Add(()=> gcHandle.Free());

            var retArea = stackalloc ulong[8+1];
            var ptr = ((int)retArea) + (8 - 1) & -8;
            InsertWasmInterop.wasmImportInsert(space.id, (nint)listPtr, (tup).Length, ptr);

            Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                    }

                    lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        public  static unsafe ulong Insert(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Space space, Span<byte> tup)
        {
            fixed (void* listPtr = tup)
            {

                var retArea = stackalloc ulong[8+1];
                var ptr = ((int)retArea) + (8 - 1) & -8;
                InsertWasmInterop.wasmImportInsert(space.id, (nint)listPtr, (tup).Length, ptr);

                Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                        break;
                    }
                    case 1: {

                        List<(string, string)>? lifted;

                        switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                            case 0: {
                                lifted = null;
                                break;
                            }

                            case 1: {

                                var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                                for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index) {
                                    nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index * 16);

                                    array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                                }

                                lifted = array;
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                        }

                        string? lifted12;

                        switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                            case 0: {
                                lifted12 = null;
                                break;
                            }

                            case 1: {

                                lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                        }

                        uint? lifted17;

                        switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                            case 0: {
                                lifted17 = null;
                                break;
                            }

                            case 1: {

                                lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                        }

                        lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                        Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted12, lifted17));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted18.IsOk)
                {
                    var tmp = lifted18.AsOk;
                    return tmp;
                }
                else
                {
                    throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
                }
            }

        }

        public  static unsafe ulong Insert(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Space space, Memory<byte> tup)
        {
            fixed (void* listPtr = tup.Span)
            {

                var retArea = stackalloc ulong[8+1];
                var ptr = ((int)retArea) + (8 - 1) & -8;
                InsertWasmInterop.wasmImportInsert(space.id, (nint)listPtr, (tup).Length, ptr);

                Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                        break;
                    }
                    case 1: {

                        List<(string, string)>? lifted;

                        switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                            case 0: {
                                lifted = null;
                                break;
                            }

                            case 1: {

                                var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                                for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index) {
                                    nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index * 16);

                                    array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                                }

                                lifted = array;
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                        }

                        string? lifted12;

                        switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                            case 0: {
                                lifted12 = null;
                                break;
                            }

                            case 1: {

                                lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                        }

                        uint? lifted17;

                        switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                            case 0: {
                                lifted17 = null;
                                break;
                            }

                            case 1: {

                                lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                        }

                        lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                        Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted12, lifted17));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted18.IsOk)
                {
                    var tmp = lifted18.AsOk;
                    return tmp;
                }
                else
                {
                    throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
                }
            }

        }

        internal static class ReplaceWasmInterop
        {
            [DllImport("tarantool:tarantool/box", EntryPoint = "replace"), WasmImportLinkage]
            internal static extern void wasmImportReplace(int p0, nint p1, int p2, nint p3);
        }

        public  static unsafe ulong Replace(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Space space, byte[] tup)
        {
            var cleanups = new List<Action>();

            var gcHandle = GCHandle.Alloc(tup, GCHandleType.Pinned);
            var listPtr = gcHandle.AddrOfPinnedObject();
            cleanups.Add(()=> gcHandle.Free());

            var retArea = stackalloc ulong[8+1];
            var ptr = ((int)retArea) + (8 - 1) & -8;
            ReplaceWasmInterop.wasmImportReplace(space.id, (nint)listPtr, (tup).Length, ptr);

            Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                    }

                    lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        public  static unsafe ulong Replace(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Space space, Span<byte> tup)
        {
            fixed (void* listPtr = tup)
            {

                var retArea = stackalloc ulong[8+1];
                var ptr = ((int)retArea) + (8 - 1) & -8;
                ReplaceWasmInterop.wasmImportReplace(space.id, (nint)listPtr, (tup).Length, ptr);

                Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                        break;
                    }
                    case 1: {

                        List<(string, string)>? lifted;

                        switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                            case 0: {
                                lifted = null;
                                break;
                            }

                            case 1: {

                                var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                                for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index) {
                                    nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index * 16);

                                    array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                                }

                                lifted = array;
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                        }

                        string? lifted12;

                        switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                            case 0: {
                                lifted12 = null;
                                break;
                            }

                            case 1: {

                                lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                        }

                        uint? lifted17;

                        switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                            case 0: {
                                lifted17 = null;
                                break;
                            }

                            case 1: {

                                lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                        }

                        lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                        Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted12, lifted17));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted18.IsOk)
                {
                    var tmp = lifted18.AsOk;
                    return tmp;
                }
                else
                {
                    throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
                }
            }

        }

        public  static unsafe ulong Replace(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Space space, Memory<byte> tup)
        {
            fixed (void* listPtr = tup.Span)
            {

                var retArea = stackalloc ulong[8+1];
                var ptr = ((int)retArea) + (8 - 1) & -8;
                ReplaceWasmInterop.wasmImportReplace(space.id, (nint)listPtr, (tup).Length, ptr);

                Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                        break;
                    }
                    case 1: {

                        List<(string, string)>? lifted;

                        switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                            case 0: {
                                lifted = null;
                                break;
                            }

                            case 1: {

                                var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                                for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index) {
                                    nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index * 16);

                                    array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                                }

                                lifted = array;
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                        }

                        string? lifted12;

                        switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                            case 0: {
                                lifted12 = null;
                                break;
                            }

                            case 1: {

                                lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                        }

                        uint? lifted17;

                        switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                            case 0: {
                                lifted17 = null;
                                break;
                            }

                            case 1: {

                                lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                        }

                        lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                        Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted12, lifted17));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted18.IsOk)
                {
                    var tmp = lifted18.AsOk;
                    return tmp;
                }
                else
                {
                    throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
                }
            }

        }

        internal static class TruncateWasmInterop
        {
            [DllImport("tarantool:tarantool/box", EntryPoint = "truncate"), WasmImportLinkage]
            internal static extern void wasmImportTruncate(int p0, nint p1);
        }

        public  static unsafe void Truncate(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Space space)
        {

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            TruncateWasmInterop.wasmImportTruncate(space.id, ptr);

            Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(new global::TarantoolWorld.None());
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        internal static class DeleteWasmInterop
        {
            [DllImport("tarantool:tarantool/box", EntryPoint = "delete"), WasmImportLinkage]
            internal static extern void wasmImportDelete(int p0, int p1, int p2, nint p3, int p4, nint p5);
        }

        public  static unsafe ulong Delete(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Index index, byte[] key)
        {
            var cleanups = new List<Action>();

            var gcHandle = GCHandle.Alloc(key, GCHandleType.Pinned);
            var listPtr = gcHandle.AddrOfPinnedObject();
            cleanups.Add(()=> gcHandle.Free());

            var retArea = stackalloc ulong[8+1];
            var ptr = ((int)retArea) + (8 - 1) & -8;
            DeleteWasmInterop.wasmImportDelete(index.id, index.spaceId, index.indexBase, (nint)listPtr, (key).Length, ptr);

            Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted19;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted19 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                            for (int index8 = 0; index8 < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index8) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index8 * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                    }

                    string? lifted13;

                    switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                        case 0: {
                            lifted13 = null;
                            break;
                        }

                        case 1: {

                            lifted13 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                    }

                    uint? lifted18;

                    switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                        case 0: {
                            lifted18 = null;
                            break;
                        }

                        case 1: {

                            lifted18 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                    }

                    lifted19 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted13, lifted18));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            if (lifted19.IsOk)
            {
                var tmp = lifted19.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted19.AsErr!, 0);
            }

        }

        public  static unsafe ulong Delete(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Index index, Span<byte> key)
        {
            fixed (void* listPtr = key)
            {

                var retArea = stackalloc ulong[8+1];
                var ptr = ((int)retArea) + (8 - 1) & -8;
                DeleteWasmInterop.wasmImportDelete(index.id, index.spaceId, index.indexBase, (nint)listPtr, (key).Length, ptr);

                Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted19;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted19 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                        break;
                    }
                    case 1: {

                        List<(string, string)>? lifted;

                        switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                            case 0: {
                                lifted = null;
                                break;
                            }

                            case 1: {

                                var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                                for (int index8 = 0; index8 < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index8) {
                                    nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index8 * 16);

                                    array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                                }

                                lifted = array;
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                        }

                        string? lifted13;

                        switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                            case 0: {
                                lifted13 = null;
                                break;
                            }

                            case 1: {

                                lifted13 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                        }

                        uint? lifted18;

                        switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                            case 0: {
                                lifted18 = null;
                                break;
                            }

                            case 1: {

                                lifted18 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                        }

                        lifted19 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                        Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted13, lifted18));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted19.IsOk)
                {
                    var tmp = lifted19.AsOk;
                    return tmp;
                }
                else
                {
                    throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted19.AsErr!, 0);
                }
            }

        }

        public  static unsafe ulong Delete(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Index index, Memory<byte> key)
        {
            fixed (void* listPtr = key.Span)
            {

                var retArea = stackalloc ulong[8+1];
                var ptr = ((int)retArea) + (8 - 1) & -8;
                DeleteWasmInterop.wasmImportDelete(index.id, index.spaceId, index.indexBase, (nint)listPtr, (key).Length, ptr);

                Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted19;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted19 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                        break;
                    }
                    case 1: {

                        List<(string, string)>? lifted;

                        switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                            case 0: {
                                lifted = null;
                                break;
                            }

                            case 1: {

                                var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                                for (int index8 = 0; index8 < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index8) {
                                    nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index8 * 16);

                                    array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                                }

                                lifted = array;
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                        }

                        string? lifted13;

                        switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                            case 0: {
                                lifted13 = null;
                                break;
                            }

                            case 1: {

                                lifted13 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                        }

                        uint? lifted18;

                        switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                            case 0: {
                                lifted18 = null;
                                break;
                            }

                            case 1: {

                                lifted18 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                        }

                        lifted19 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                        Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted13, lifted18));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted19.IsOk)
                {
                    var tmp = lifted19.AsOk;
                    return tmp;
                }
                else
                {
                    throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted19.AsErr!, 0);
                }
            }

        }

        internal static class UpdateWasmInterop
        {
            [DllImport("tarantool:tarantool/box", EntryPoint = "update"), WasmImportLinkage]
            internal static extern void wasmImportUpdate(int p0, int p1, int p2, nint p3, int p4, nint p5, int p6, nint p7);
        }

        public  static unsafe ulong Update(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Index index, byte[] key, byte[] ops)
        {
            var cleanups = new List<Action>();

            var gcHandle = GCHandle.Alloc(key, GCHandleType.Pinned);
            var listPtr = gcHandle.AddrOfPinnedObject();
            cleanups.Add(()=> gcHandle.Free());

            var gcHandle1 = GCHandle.Alloc(ops, GCHandleType.Pinned);
            var listPtr0 = gcHandle1.AddrOfPinnedObject();
            cleanups.Add(()=> gcHandle1.Free());

            var retArea = stackalloc ulong[8+1];
            var ptr = ((int)retArea) + (8 - 1) & -8;
            UpdateWasmInterop.wasmImportUpdate(index.id, index.spaceId, index.indexBase, (nint)listPtr, (key).Length, (nint)listPtr0, (ops).Length, ptr);

            Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted21;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted21 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                            for (int index10 = 0; index10 < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index10) {
                                nint basePtr9 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index10 * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                    }

                    string? lifted15;

                    switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                        case 0: {
                            lifted15 = null;
                            break;
                        }

                        case 1: {

                            lifted15 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                    }

                    uint? lifted20;

                    switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                        case 0: {
                            lifted20 = null;
                            break;
                        }

                        case 1: {

                            lifted20 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                    }

                    lifted21 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted15, lifted20));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            if (lifted21.IsOk)
            {
                var tmp = lifted21.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted21.AsErr!, 0);
            }

        }

        public  static unsafe ulong Update(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Index index, Span<byte> key, Span<byte> ops)
        {
            fixed (void* listPtr = key, listPtr0 = ops)
            {

                var retArea = stackalloc ulong[8+1];
                var ptr = ((int)retArea) + (8 - 1) & -8;
                UpdateWasmInterop.wasmImportUpdate(index.id, index.spaceId, index.indexBase, (nint)listPtr, (key).Length, (nint)listPtr0, (ops).Length, ptr);

                Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted21;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted21 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                        break;
                    }
                    case 1: {

                        List<(string, string)>? lifted;

                        switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                            case 0: {
                                lifted = null;
                                break;
                            }

                            case 1: {

                                var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                                for (int index10 = 0; index10 < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index10) {
                                    nint basePtr9 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index10 * 16);

                                    array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 12), 4)))));
                                }

                                lifted = array;
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                        }

                        string? lifted15;

                        switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                            case 0: {
                                lifted15 = null;
                                break;
                            }

                            case 1: {

                                lifted15 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                        }

                        uint? lifted20;

                        switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                            case 0: {
                                lifted20 = null;
                                break;
                            }

                            case 1: {

                                lifted20 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                        }

                        lifted21 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                        Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted15, lifted20));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted21.IsOk)
                {
                    var tmp = lifted21.AsOk;
                    return tmp;
                }
                else
                {
                    throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted21.AsErr!, 0);
                }
            }

        }

        public  static unsafe ulong Update(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Index index, Memory<byte> key, Memory<byte> ops)
        {
            fixed (void* listPtr = key.Span, listPtr0 = ops.Span)
            {

                var retArea = stackalloc ulong[8+1];
                var ptr = ((int)retArea) + (8 - 1) & -8;
                UpdateWasmInterop.wasmImportUpdate(index.id, index.spaceId, index.indexBase, (nint)listPtr, (key).Length, (nint)listPtr0, (ops).Length, ptr);

                Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted21;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted21 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                        break;
                    }
                    case 1: {

                        List<(string, string)>? lifted;

                        switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                            case 0: {
                                lifted = null;
                                break;
                            }

                            case 1: {

                                var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                                for (int index10 = 0; index10 < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index10) {
                                    nint basePtr9 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index10 * 16);

                                    array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 12), 4)))));
                                }

                                lifted = array;
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                        }

                        string? lifted15;

                        switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                            case 0: {
                                lifted15 = null;
                                break;
                            }

                            case 1: {

                                lifted15 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                        }

                        uint? lifted20;

                        switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                            case 0: {
                                lifted20 = null;
                                break;
                            }

                            case 1: {

                                lifted20 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                        }

                        lifted21 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                        Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted15, lifted20));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted21.IsOk)
                {
                    var tmp = lifted21.AsOk;
                    return tmp;
                }
                else
                {
                    throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted21.AsErr!, 0);
                }
            }

        }

        internal static class UpsertWasmInterop
        {
            [DllImport("tarantool:tarantool/box", EntryPoint = "upsert"), WasmImportLinkage]
            internal static extern void wasmImportUpsert(int p0, int p1, int p2, nint p3, int p4, nint p5, int p6, nint p7);
        }

        public  static unsafe ulong Upsert(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Index index, byte[] tup, byte[] ops)
        {
            var cleanups = new List<Action>();

            var gcHandle = GCHandle.Alloc(tup, GCHandleType.Pinned);
            var listPtr = gcHandle.AddrOfPinnedObject();
            cleanups.Add(()=> gcHandle.Free());

            var gcHandle1 = GCHandle.Alloc(ops, GCHandleType.Pinned);
            var listPtr0 = gcHandle1.AddrOfPinnedObject();
            cleanups.Add(()=> gcHandle1.Free());

            var retArea = stackalloc ulong[8+1];
            var ptr = ((int)retArea) + (8 - 1) & -8;
            UpsertWasmInterop.wasmImportUpsert(index.id, index.spaceId, index.indexBase, (nint)listPtr, (tup).Length, (nint)listPtr0, (ops).Length, ptr);

            Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted21;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted21 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                            for (int index10 = 0; index10 < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index10) {
                                nint basePtr9 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index10 * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                    }

                    string? lifted15;

                    switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                        case 0: {
                            lifted15 = null;
                            break;
                        }

                        case 1: {

                            lifted15 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                    }

                    uint? lifted20;

                    switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                        case 0: {
                            lifted20 = null;
                            break;
                        }

                        case 1: {

                            lifted20 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                    }

                    lifted21 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted15, lifted20));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            if (lifted21.IsOk)
            {
                var tmp = lifted21.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted21.AsErr!, 0);
            }

        }

        public  static unsafe ulong Upsert(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Index index, Span<byte> tup, Span<byte> ops)
        {
            fixed (void* listPtr = tup, listPtr0 = ops)
            {

                var retArea = stackalloc ulong[8+1];
                var ptr = ((int)retArea) + (8 - 1) & -8;
                UpsertWasmInterop.wasmImportUpsert(index.id, index.spaceId, index.indexBase, (nint)listPtr, (tup).Length, (nint)listPtr0, (ops).Length, ptr);

                Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted21;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted21 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                        break;
                    }
                    case 1: {

                        List<(string, string)>? lifted;

                        switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                            case 0: {
                                lifted = null;
                                break;
                            }

                            case 1: {

                                var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                                for (int index10 = 0; index10 < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index10) {
                                    nint basePtr9 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index10 * 16);

                                    array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 12), 4)))));
                                }

                                lifted = array;
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                        }

                        string? lifted15;

                        switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                            case 0: {
                                lifted15 = null;
                                break;
                            }

                            case 1: {

                                lifted15 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                        }

                        uint? lifted20;

                        switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                            case 0: {
                                lifted20 = null;
                                break;
                            }

                            case 1: {

                                lifted20 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                        }

                        lifted21 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                        Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted15, lifted20));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted21.IsOk)
                {
                    var tmp = lifted21.AsOk;
                    return tmp;
                }
                else
                {
                    throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted21.AsErr!, 0);
                }
            }

        }

        public  static unsafe ulong Upsert(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Index index, Memory<byte> tup, Memory<byte> ops)
        {
            fixed (void* listPtr = tup.Span, listPtr0 = ops.Span)
            {

                var retArea = stackalloc ulong[8+1];
                var ptr = ((int)retArea) + (8 - 1) & -8;
                UpsertWasmInterop.wasmImportUpsert(index.id, index.spaceId, index.indexBase, (nint)listPtr, (tup).Length, (nint)listPtr0, (ops).Length, ptr);

                Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted21;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted21 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                        break;
                    }
                    case 1: {

                        List<(string, string)>? lifted;

                        switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                            case 0: {
                                lifted = null;
                                break;
                            }

                            case 1: {

                                var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                                for (int index10 = 0; index10 < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index10) {
                                    nint basePtr9 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index10 * 16);

                                    array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr9 + 12), 4)))));
                                }

                                lifted = array;
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                        }

                        string? lifted15;

                        switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                            case 0: {
                                lifted15 = null;
                                break;
                            }

                            case 1: {

                                lifted15 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                        }

                        uint? lifted20;

                        switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                            case 0: {
                                lifted20 = null;
                                break;
                            }

                            case 1: {

                                lifted20 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                        }

                        lifted21 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                        Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted15, lifted20));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted21.IsOk)
                {
                    var tmp = lifted21.AsOk;
                    return tmp;
                }
                else
                {
                    throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted21.AsErr!, 0);
                }
            }

        }

    }
}
