// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System.Text;
using System.Runtime.InteropServices;

namespace TarantoolWorld.wit.imports.tarantool.tarantool
{
    public static class SayInterop {

        internal static class SayWasmInterop
        {
            [DllImport("tarantool:tarantool/say", EntryPoint = "say"), WasmImportLinkage]
            internal static extern void wasmImportSay(int p0, nint p1, int p2);
        }

        public  static unsafe void Say(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.LogLevel level, string msg)
        {
            var cleanups = new List<Action>();

            var utf8Bytes = Encoding.UTF8.GetBytes(msg);
            var length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            var interopString = gcHandle.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle.Free());
            SayWasmInterop.wasmImportSay((int)level, interopString.ToInt32(), length);

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }

        }

        internal static class SayErrorWasmInterop
        {
            [DllImport("tarantool:tarantool/say", EntryPoint = "say-error"), WasmImportLinkage]
            internal static extern void wasmImportSayError(nint p0, int p1);
        }

        public  static unsafe void SayError(string msg)
        {
            var cleanups = new List<Action>();

            var utf8Bytes = Encoding.UTF8.GetBytes(msg);
            var length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            var interopString = gcHandle.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle.Free());
            SayErrorWasmInterop.wasmImportSayError(interopString.ToInt32(), length);

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }

        }

        internal static class SayCritWasmInterop
        {
            [DllImport("tarantool:tarantool/say", EntryPoint = "say-crit"), WasmImportLinkage]
            internal static extern void wasmImportSayCrit(nint p0, int p1);
        }

        public  static unsafe void SayCrit(string msg)
        {
            var cleanups = new List<Action>();

            var utf8Bytes = Encoding.UTF8.GetBytes(msg);
            var length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            var interopString = gcHandle.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle.Free());
            SayCritWasmInterop.wasmImportSayCrit(interopString.ToInt32(), length);

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }

        }

        internal static class SayWarnWasmInterop
        {
            [DllImport("tarantool:tarantool/say", EntryPoint = "say-warn"), WasmImportLinkage]
            internal static extern void wasmImportSayWarn(nint p0, int p1);
        }

        public  static unsafe void SayWarn(string msg)
        {
            var cleanups = new List<Action>();

            var utf8Bytes = Encoding.UTF8.GetBytes(msg);
            var length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            var interopString = gcHandle.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle.Free());
            SayWarnWasmInterop.wasmImportSayWarn(interopString.ToInt32(), length);

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }

        }

        internal static class SayInfoWasmInterop
        {
            [DllImport("tarantool:tarantool/say", EntryPoint = "say-info"), WasmImportLinkage]
            internal static extern void wasmImportSayInfo(nint p0, int p1);
        }

        public  static unsafe void SayInfo(string msg)
        {
            var cleanups = new List<Action>();

            var utf8Bytes = Encoding.UTF8.GetBytes(msg);
            var length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            var interopString = gcHandle.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle.Free());
            SayInfoWasmInterop.wasmImportSayInfo(interopString.ToInt32(), length);

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }

        }

        internal static class SayVerboseWasmInterop
        {
            [DllImport("tarantool:tarantool/say", EntryPoint = "say-verbose"), WasmImportLinkage]
            internal static extern void wasmImportSayVerbose(nint p0, int p1);
        }

        public  static unsafe void SayVerbose(string msg)
        {
            var cleanups = new List<Action>();

            var utf8Bytes = Encoding.UTF8.GetBytes(msg);
            var length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            var interopString = gcHandle.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle.Free());
            SayVerboseWasmInterop.wasmImportSayVerbose(interopString.ToInt32(), length);

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }

        }

        internal static class SayDebugWasmInterop
        {
            [DllImport("tarantool:tarantool/say", EntryPoint = "say-debug"), WasmImportLinkage]
            internal static extern void wasmImportSayDebug(nint p0, int p1);
        }

        public  static unsafe void SayDebug(string msg)
        {
            var cleanups = new List<Action>();

            var utf8Bytes = Encoding.UTF8.GetBytes(msg);
            var length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            var interopString = gcHandle.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle.Free());
            SayDebugWasmInterop.wasmImportSayDebug(interopString.ToInt32(), length);

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }

        }

        internal static class SaySyserrorWasmInterop
        {
            [DllImport("tarantool:tarantool/say", EntryPoint = "say-syserror"), WasmImportLinkage]
            internal static extern void wasmImportSaySyserror(nint p0, int p1);
        }

        public  static unsafe void SaySyserror(string msg)
        {
            var cleanups = new List<Action>();

            var utf8Bytes = Encoding.UTF8.GetBytes(msg);
            var length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            var interopString = gcHandle.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle.Free());
            SaySyserrorWasmInterop.wasmImportSaySyserror(interopString.ToInt32(), length);

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }

        }

    }
}
