// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System.Runtime.InteropServices;
using System.Text;

namespace TarantoolWorld.wit.imports.tarantool.tarantool
{
    public static class TxnInterop {

        internal static class TxnIdWasmInterop
        {
            [DllImport("tarantool:tarantool/txn", EntryPoint = "txn-id"), WasmImportLinkage]
            internal static extern long wasmImportTxnId();
        }

        public  static unsafe long TxnId()
        {
            var result =  TxnIdWasmInterop.wasmImportTxnId();
            return result;

        }

        internal static class TxnIsolationWasmInterop
        {
            [DllImport("tarantool:tarantool/txn", EntryPoint = "txn-isolation"), WasmImportLinkage]
            internal static extern int wasmImportTxnIsolation();
        }

        public  static unsafe global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.TxnIsolationLevel TxnIsolation()
        {
            var result =  TxnIsolationWasmInterop.wasmImportTxnIsolation();
            return (global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.TxnIsolationLevel)result;

        }

        internal static class TxnWasmInterop
        {
            [DllImport("tarantool:tarantool/txn", EntryPoint = "txn"), WasmImportLinkage]
            internal static extern int wasmImportTxn();
        }

        public  static unsafe bool Txn()
        {
            var result =  TxnWasmInterop.wasmImportTxn();
            return (result != 0);

        }

        internal static class BeginWasmInterop
        {
            [DllImport("tarantool:tarantool/txn", EntryPoint = "begin"), WasmImportLinkage]
            internal static extern void wasmImportBegin(nint p0);
        }

        public  static unsafe void Begin()
        {

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            BeginWasmInterop.wasmImportBegin(ptr);

            Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(new global::TarantoolWorld.None());
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        internal static class CommitWasmInterop
        {
            [DllImport("tarantool:tarantool/txn", EntryPoint = "commit"), WasmImportLinkage]
            internal static extern void wasmImportCommit(nint p0);
        }

        public  static unsafe void Commit()
        {

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            CommitWasmInterop.wasmImportCommit(ptr);

            Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(new global::TarantoolWorld.None());
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        internal static class RollbackWasmInterop
        {
            [DllImport("tarantool:tarantool/txn", EntryPoint = "rollback"), WasmImportLinkage]
            internal static extern void wasmImportRollback(nint p0);
        }

        public  static unsafe void Rollback()
        {

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            RollbackWasmInterop.wasmImportRollback(ptr);

            Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(new global::TarantoolWorld.None());
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        internal static class TxnSetIsolationWasmInterop
        {
            [DllImport("tarantool:tarantool/txn", EntryPoint = "txn-set-isolation"), WasmImportLinkage]
            internal static extern void wasmImportTxnSetIsolation(int p0, nint p1);
        }

        public  static unsafe void TxnSetIsolation(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.TxnIsolationLevel isolation)
        {

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            TxnSetIsolationWasmInterop.wasmImportTxnSetIsolation((int)isolation, ptr);

            Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(new global::TarantoolWorld.None());
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        internal static class TxnMakeSyncWasmInterop
        {
            [DllImport("tarantool:tarantool/txn", EntryPoint = "txn-make-sync"), WasmImportLinkage]
            internal static extern void wasmImportTxnMakeSync();
        }

        public  static unsafe void TxnMakeSync()
        {
            TxnMakeSyncWasmInterop.wasmImportTxnMakeSync();

        }

    }
}
