// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System.Runtime.InteropServices;
using System.Text;

namespace TarantoolWorld.wit.imports.tarantool.tarantool
{
    public static class TupleFormatInterop {

        internal static class DefaultWasmInterop
        {
            [DllImport("tarantool:tarantool/tuple-format", EntryPoint = "default"), WasmImportLinkage]
            internal static extern long wasmImportDefault();
        }

        public  static unsafe ulong Default()
        {
            var result =  DefaultWasmInterop.wasmImportDefault();
            return unchecked((ulong)(result));

        }

        internal static class NewWasmInterop
        {
            [DllImport("tarantool:tarantool/tuple-format", EntryPoint = "new"), WasmImportLinkage]
            internal static extern void wasmImportNew(nint p0, int p1, nint p2);
        }

        public  static unsafe ulong New(List<ulong> keyDefs)
        {
            var cleanups = new List<Action>();

            void* address;
            if ((8 * keyDefs.Count) < 1024) {
                var retArea = stackalloc ulong[(1*keyDefs.Count)+1];
                address = (void*)(((int)retArea) + (8 - 1) & -8);
            }
            else
            {
                var bufferSize = 8 * (nuint)keyDefs.Count;
                address = NativeMemory.AlignedAlloc(bufferSize, 8);
                cleanups.Add(()=> NativeMemory.AlignedFree(address));
            }

            for (int index = 0; index < keyDefs.Count; ++index) {
                ulong element = keyDefs[index];
                int basePtr = (int)address + (index * 8);
                BitConverter.TryWriteBytes(new Span<byte>((void*)(basePtr + 0), 8), unchecked((long)unchecked((long)(element))));

            }

            var retArea0 = stackalloc ulong[8+1];
            var ptr = ((int)retArea0) + (8 - 1) & -8;
            NewWasmInterop.wasmImportNew((int)address, keyDefs.Count, ptr);

            Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted22;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted22 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                            for (int index11 = 0; index11 < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index11) {
                                nint basePtr10 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index11 * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr10 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr10 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr10 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr10 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                    }

                    string? lifted16;

                    switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                        case 0: {
                            lifted16 = null;
                            break;
                        }

                        case 1: {

                            lifted16 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                    }

                    uint? lifted21;

                    switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                        case 0: {
                            lifted21 = null;
                            break;
                        }

                        case 1: {

                            lifted21 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                    }

                    lifted22 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted16, lifted21));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            if (lifted22.IsOk)
            {
                var tmp = lifted22.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted22.AsErr!, 0);
            }

        }

        internal static class RefWasmInterop
        {
            [DllImport("tarantool:tarantool/tuple-format", EntryPoint = "ref"), WasmImportLinkage]
            internal static extern void wasmImportRef(long p0);
        }

        public  static unsafe void Ref(ulong tf)
        {
            RefWasmInterop.wasmImportRef(unchecked((long)(tf)));

        }

        internal static class UnrefWasmInterop
        {
            [DllImport("tarantool:tarantool/tuple-format", EntryPoint = "unref"), WasmImportLinkage]
            internal static extern void wasmImportUnref(long p0);
        }

        public  static unsafe void Unref(ulong tf)
        {
            UnrefWasmInterop.wasmImportUnref(unchecked((long)(tf)));

        }

    }
}
