// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System.Runtime.InteropServices;
using System.Text;

namespace TarantoolWorld.wit.imports.tarantool.tarantool;

public interface ITypes {

    public enum LogLevel {
        S_FATAL, S_SYSERROR, S_ERROR, S_CRIT, S_WARN, S_INFO, S_VERBOSE, S_DEBUG
    }

    public enum IteratorType {
        ITER_EQ, ITER_REQ, ITER_ALL, ITER_LT, ITER_LE, ITER_GE, ITER_GT, ITER_BITS_ALL_SET, ITER_BITS_ANY_SET, ITER_BITS_ALL_NOT_SET, ITER_OVERLAPS, ITER_NEIGHBOR, ITER_NP, ITER_PP
    }

    public enum TxnIsolationLevel {
        TXN_ISOLATION_DEFAULT, TXN_ISOLATION_READ_COMMITTED, TXN_ISOLATION_READ_CONFIRMED, TXN_ISOLATION_BEST_EFFORT, TXN_ISOLATION_LINEARIZABLE
    }

    public enum IndexType {
        TREE, HASH, BITSET, RTREE
    }

    public enum KeyPartFlags : byte {
        IS_NULLABLE = 1 << 0,
        EXCLUDE_NULL = 1 << 1,
    }

    public class FieldIdentifier {
        public readonly byte Tag;
        private readonly object? value;

        private FieldIdentifier(byte tag, object? value) {
            this.Tag = tag;
            this.value = value;
        }

        public static FieldIdentifier Number(uint number) {
            return new FieldIdentifier(Tags.Number, number);
        }

        public static FieldIdentifier Name(string name) {
            return new FieldIdentifier(Tags.Name, name);
        }

        public uint AsNumber
        {
            get
            {
                if (Tag == Tags.Number)
                return (uint)value!;
                else
                throw new ArgumentException("expected Number, got " + Tag);
            }
        }

        public string AsName
        {
            get
            {
                if (Tag == Tags.Name)
                return (string)value!;
                else
                throw new ArgumentException("expected Name, got " + Tag);
            }
        }

        public class Tags {
            public const byte Number = 0;
            public const byte Name = 1;
        }
    }

    public class KeyPartDef {
        public readonly FieldIdentifier field;
        public readonly string fieldType;
        public readonly string? collation;
        public readonly string? path;
        public readonly KeyPartFlags flags;

        public KeyPartDef(FieldIdentifier field, string fieldType, string? collation, string? path, KeyPartFlags flags) {
            this.field = field;
            this.fieldType = fieldType;
            this.collation = collation;
            this.path = path;
            this.flags = flags;
        }
    }

    public class BoxError {
        public readonly string message;
        public readonly string type;
        public readonly uint code;
        public readonly List<(string, string)>? payload;
        public readonly string? file;
        public readonly uint? line;

        public BoxError(string message, string type, uint code, List<(string, string)>? payload, string? file, uint? line) {
            this.message = message;
            this.type = type;
            this.code = code;
            this.payload = payload;
            this.file = file;
            this.line = line;
        }
    }

    public class Index {
        public readonly int id;
        public readonly int spaceId;
        public readonly int indexBase;

        public Index(int id, int spaceId, int indexBase) {
            this.id = id;
            this.spaceId = spaceId;
            this.indexBase = indexBase;
        }
    }

    public class Sequence {
        public readonly int id;

        public Sequence(int id) {
            this.id = id;
        }
    }

    public class Space {
        public readonly int id;

        public Space(int id) {
            this.id = id;
        }
    }

    public class SequenceOptions {
        public readonly long start;
        public readonly long increment;
        public readonly long min;
        public readonly long max;
        public readonly bool cycle;

        public SequenceOptions(long start, long increment, long min, long max, bool cycle) {
            this.start = start;
            this.increment = increment;
            this.min = min;
            this.max = max;
            this.cycle = cycle;
        }
    }

    public class Peer {
        public readonly string host;
        public readonly uint port;

        public Peer(string host, uint port) {
            this.host = host;
            this.port = port;
        }
    }

    public class Session {
        public readonly long id;

        public Session(long id) {
            this.id = id;
        }
    }

    public class SelectOpts {
        public readonly IteratorType? iterator;
        public readonly uint? limit;
        public readonly uint? offset;
        public readonly long? after;
        public readonly bool? fetchPos;

        public SelectOpts(IteratorType? iterator, uint? limit, uint? offset, long? after, bool? fetchPos) {
            this.iterator = iterator;
            this.limit = limit;
            this.offset = offset;
            this.after = after;
            this.fetchPos = fetchPos;
        }
    }

    public class PairsOpts {
        public readonly byte[]? key;
        public readonly IteratorType? iterator;
        public readonly long? after;

        public PairsOpts(byte[]? key, IteratorType? iterator, long? after) {
            this.key = key;
            this.iterator = iterator;
            this.after = after;
        }
    }

    public class UpdateOp {
        public readonly uint fieldNo;
        public readonly string op;
        public readonly byte[] operand;

        public UpdateOp(uint fieldNo, string op, byte[] operand) {
            this.fieldNo = fieldNo;
            this.op = op;
            this.operand = operand;
        }
    }

    public class IndexStat {
        public readonly long bsize;
        public readonly long len;

        public IndexStat(long bsize, long len) {
            this.bsize = bsize;
            this.len = len;
        }
    }

    public class Iterator: IDisposable {
        internal int Handle { get; set; }

        public readonly record struct THandle(int Handle);

        public Iterator(THandle handle) {
            Handle = handle.Handle;
        }

        public void Dispose() {
            Dispose(true);
        }

        [DllImport("tarantool:tarantool/types", EntryPoint = "[resource-drop]iterator"), WasmImportLinkage]
        private static extern void wasmImportResourceDrop(int p0);

        protected virtual void Dispose(bool disposing) {
            if (disposing && Handle != 0) {
                wasmImportResourceDrop(Handle);
                Handle = 0;
            }
        }

        internal static class NewIteratorWasmInterop
        {
            [DllImport("tarantool:tarantool/types", EntryPoint = "[static]iterator.new-iterator"), WasmImportLinkage]
            internal static extern void wasmImportNewIterator(int p0, int p1, int p2, int p3, nint p4, int p5, nint p6);
        }

        public  static unsafe global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator NewIterator(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Index index, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.IteratorType iteratorType, byte[] key)
        {
            var cleanups = new List<Action>();

            var gcHandle = GCHandle.Alloc(key, GCHandleType.Pinned);
            var listPtr = gcHandle.AddrOfPinnedObject();
            cleanups.Add(()=> gcHandle.Free());

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            NewIteratorWasmInterop.wasmImportNewIterator(index.id, index.spaceId, index.indexBase, (int)iteratorType, (nint)listPtr, (key).Length, ptr);

            Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted19;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {
                    var resource = new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator.THandle(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4))));

                    lifted19 = Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(resource);
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index8 = 0; index8 < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index8) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index8 * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted13;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted13 = null;
                            break;
                        }

                        case 1: {

                            lifted13 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted18;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted18 = null;
                            break;
                        }

                        case 1: {

                            lifted18 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted19 = Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted13, lifted18));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            if (lifted19.IsOk)
            {
                var tmp = lifted19.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted19.AsErr!, 0);
            }

        }

        public  static unsafe global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator NewIterator(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Index index, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.IteratorType iteratorType, Span<byte> key)
        {
            fixed (void* listPtr = key)
            {

                var retArea = stackalloc uint[14+1];
                var ptr = ((int)retArea) + (4 - 1) & -4;
                NewIteratorWasmInterop.wasmImportNewIterator(index.id, index.spaceId, index.indexBase, (int)iteratorType, (nint)listPtr, (key).Length, ptr);

                Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted19;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {
                        var resource = new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator.THandle(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4))));

                        lifted19 = Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(resource);
                        break;
                    }
                    case 1: {

                        List<(string, string)>? lifted;

                        switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                            case 0: {
                                lifted = null;
                                break;
                            }

                            case 1: {

                                var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                                for (int index8 = 0; index8 < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index8) {
                                    nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index8 * 16);

                                    array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                                }

                                lifted = array;
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                        }

                        string? lifted13;

                        switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                            case 0: {
                                lifted13 = null;
                                break;
                            }

                            case 1: {

                                lifted13 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                        }

                        uint? lifted18;

                        switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                            case 0: {
                                lifted18 = null;
                                break;
                            }

                            case 1: {

                                lifted18 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                        }

                        lifted19 = Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                        Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted13, lifted18));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted19.IsOk)
                {
                    var tmp = lifted19.AsOk;
                    return tmp;
                }
                else
                {
                    throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted19.AsErr!, 0);
                }
            }

        }

        public  static unsafe global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator NewIterator(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Index index, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.IteratorType iteratorType, Memory<byte> key)
        {
            fixed (void* listPtr = key.Span)
            {

                var retArea = stackalloc uint[14+1];
                var ptr = ((int)retArea) + (4 - 1) & -4;
                NewIteratorWasmInterop.wasmImportNewIterator(index.id, index.spaceId, index.indexBase, (int)iteratorType, (nint)listPtr, (key).Length, ptr);

                Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted19;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {
                        var resource = new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator.THandle(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4))));

                        lifted19 = Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(resource);
                        break;
                    }
                    case 1: {

                        List<(string, string)>? lifted;

                        switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                            case 0: {
                                lifted = null;
                                break;
                            }

                            case 1: {

                                var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                                for (int index8 = 0; index8 < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index8) {
                                    nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index8 * 16);

                                    array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                                }

                                lifted = array;
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                        }

                        string? lifted13;

                        switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                            case 0: {
                                lifted13 = null;
                                break;
                            }

                            case 1: {

                                lifted13 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                        }

                        uint? lifted18;

                        switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                            case 0: {
                                lifted18 = null;
                                break;
                            }

                            case 1: {

                                lifted18 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                                break;
                            }

                            default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                        }

                        lifted19 = Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Iterator, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                        Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted13, lifted18));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted19.IsOk)
                {
                    var tmp = lifted19.AsOk;
                    return tmp;
                }
                else
                {
                    throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted19.AsErr!, 0);
                }
            }

        }

        internal static class NextWasmInterop
        {
            [DllImport("tarantool:tarantool/types", EntryPoint = "[method]iterator.next"), WasmImportLinkage]
            internal static extern void wasmImportNext(int p0, nint p1);
        }

        public   unsafe ulong Next()
        {
            var handle = this.Handle;

            var retArea = stackalloc ulong[8+1];
            var ptr = ((int)retArea) + (8 - 1) & -8;
            NextWasmInterop.wasmImportNext(handle, ptr);

            Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                    }

                    lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

    }

    public class TupleIterator: IDisposable {
        internal int Handle { get; set; }

        public readonly record struct THandle(int Handle);

        public TupleIterator(THandle handle) {
            Handle = handle.Handle;
        }

        public void Dispose() {
            Dispose(true);
        }

        [DllImport("tarantool:tarantool/types", EntryPoint = "[resource-drop]tuple-iterator"), WasmImportLinkage]
        private static extern void wasmImportResourceDrop(int p0);

        protected virtual void Dispose(bool disposing) {
            if (disposing && Handle != 0) {
                wasmImportResourceDrop(Handle);
                Handle = 0;
            }
        }

        internal static class NewTupleIteratorWasmInterop
        {
            [DllImport("tarantool:tarantool/types", EntryPoint = "[static]tuple-iterator.new-tuple-iterator"), WasmImportLinkage]
            internal static extern void wasmImportNewTupleIterator(long p0, nint p1);
        }

        public  static unsafe global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.TupleIterator NewTupleIterator(ulong tuple)
        {

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            NewTupleIteratorWasmInterop.wasmImportNewTupleIterator(unchecked((long)(tuple)), ptr);

            Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.TupleIterator, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {
                    var resource = new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.TupleIterator(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.TupleIterator.THandle(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4))));

                    lifted18 = Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.TupleIterator, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(resource);
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted18 = Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.TupleIterator, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        internal static class PositionWasmInterop
        {
            [DllImport("tarantool:tarantool/types", EntryPoint = "[method]tuple-iterator.position"), WasmImportLinkage]
            internal static extern int wasmImportPosition(int p0);
        }

        public   unsafe uint Position()
        {
            var handle = this.Handle;
            var result =  PositionWasmInterop.wasmImportPosition(handle);
            return unchecked((uint)(result));

        }

        internal static class RewindWasmInterop
        {
            [DllImport("tarantool:tarantool/types", EntryPoint = "[method]tuple-iterator.rewind"), WasmImportLinkage]
            internal static extern void wasmImportRewind(int p0);
        }

        public   unsafe void Rewind()
        {
            var handle = this.Handle;
            RewindWasmInterop.wasmImportRewind(handle);

        }

        internal static class SeekWasmInterop
        {
            [DllImport("tarantool:tarantool/types", EntryPoint = "[method]tuple-iterator.seek"), WasmImportLinkage]
            internal static extern void wasmImportSeek(int p0, int p1, nint p2);
        }

        public   unsafe ulong Seek(uint pos)
        {
            var handle = this.Handle;

            var retArea = stackalloc ulong[8+1];
            var ptr = ((int)retArea) + (8 - 1) & -8;
            SeekWasmInterop.wasmImportSeek(handle, unchecked((int)(pos)), ptr);

            Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                    }

                    lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        internal static class NextWasmInterop
        {
            [DllImport("tarantool:tarantool/types", EntryPoint = "[method]tuple-iterator.next"), WasmImportLinkage]
            internal static extern void wasmImportNext(int p0, nint p1);
        }

        public   unsafe ulong Next()
        {
            var handle = this.Handle;

            var retArea = stackalloc ulong[8+1];
            var ptr = ((int)retArea) + (8 - 1) & -8;
            NextWasmInterop.wasmImportNext(handle, ptr);

            Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                    }

                    lifted18 = Result<ulong, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

    }

}
