// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System.Runtime.InteropServices;
using System.Text;

namespace TarantoolWorld.wit.imports.tarantool.tarantool
{
    public static class SequenceInterop {

        internal static class NextWasmInterop
        {
            [DllImport("tarantool:tarantool/sequence", EntryPoint = "next"), WasmImportLinkage]
            internal static extern void wasmImportNext(int p0, nint p1);
        }

        public  static unsafe long Next(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Sequence seq)
        {

            var retArea = stackalloc ulong[8+1];
            var ptr = ((int)retArea) + (8 - 1) & -8;
            NextWasmInterop.wasmImportNext(seq.id, ptr);

            Result<long, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<long, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                    }

                    lifted18 = Result<long, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        internal static class CurrentWasmInterop
        {
            [DllImport("tarantool:tarantool/sequence", EntryPoint = "current"), WasmImportLinkage]
            internal static extern void wasmImportCurrent(int p0, nint p1);
        }

        public  static unsafe long Current(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Sequence seq)
        {

            var retArea = stackalloc ulong[8+1];
            var ptr = ((int)retArea) + (8 - 1) & -8;
            CurrentWasmInterop.wasmImportCurrent(seq.id, ptr);

            Result<long, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<long, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 28), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 36), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 28), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 40), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 48), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 40), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 52), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 56), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 52), 1)[0]));
                    }

                    lifted18 = Result<long, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 24), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        internal static class SetWasmInterop
        {
            [DllImport("tarantool:tarantool/sequence", EntryPoint = "set"), WasmImportLinkage]
            internal static extern void wasmImportSet(int p0, long p1, nint p2);
        }

        public  static unsafe void Set(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Sequence seq, long value)
        {

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            SetWasmInterop.wasmImportSet(seq.id, value, ptr);

            Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(new global::TarantoolWorld.None());
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        internal static class ResetWasmInterop
        {
            [DllImport("tarantool:tarantool/sequence", EntryPoint = "reset"), WasmImportLinkage]
            internal static extern void wasmImportReset(int p0, nint p1);
        }

        public  static unsafe void Reset(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Sequence seq)
        {

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            ResetWasmInterop.wasmImportReset(seq.id, ptr);

            Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(new global::TarantoolWorld.None());
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        internal static class CreateWasmInterop
        {
            [DllImport("tarantool:tarantool/sequence", EntryPoint = "create"), WasmImportLinkage]
            internal static extern void wasmImportCreate(nint p0, int p1, int p2, long p3, long p4, long p5, long p6, int p7, nint p8);
        }

        public  static unsafe global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Sequence Create(string name, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.SequenceOptions? opts)
        {
            var cleanups = new List<Action>();

            var utf8Bytes = Encoding.UTF8.GetBytes(name);
            var length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            var interopString = gcHandle.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle.Free());

            int lowered;
            long lowered3;
            long lowered4;
            long lowered5;
            long lowered6;
            int lowered7;

            if (opts != null) {
                var payload2 = (global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.SequenceOptions) opts;

                lowered = 1;
                lowered3 = payload2.start;
                lowered4 = payload2.increment;
                lowered5 = payload2.min;
                lowered6 = payload2.max;
                lowered7 = (payload2.cycle ? 1 : 0);

            } else {

                lowered = 0;
                lowered3 = 0L;
                lowered4 = 0L;
                lowered5 = 0L;
                lowered6 = 0L;
                lowered7 = 0;

            }

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            CreateWasmInterop.wasmImportCreate(interopString.ToInt32(), length, lowered, lowered3, lowered4, lowered5, lowered6, lowered7, ptr);

            Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Sequence, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted28;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted28 = Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Sequence, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Sequence (
                    BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4))));
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                nint basePtr17 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr17 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr17 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr17 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr17 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted22;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted22 = null;
                            break;
                        }

                        case 1: {

                            lifted22 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted27;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted27 = null;
                            break;
                        }

                        case 1: {

                            lifted27 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted28 = Result<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Sequence, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted22, lifted27));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            if (lifted28.IsOk)
            {
                var tmp = lifted28.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted28.AsErr!, 0);
            }

        }

        internal static class AlterWasmInterop
        {
            [DllImport("tarantool:tarantool/sequence", EntryPoint = "alter"), WasmImportLinkage]
            internal static extern void wasmImportAlter(int p0, long p1, long p2, long p3, long p4, int p5, nint p6);
        }

        public  static unsafe void Alter(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Sequence seq, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.SequenceOptions opts)
        {

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            AlterWasmInterop.wasmImportAlter(seq.id, opts.start, opts.increment, opts.min, opts.max, (opts.cycle ? 1 : 0), ptr);

            Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(new global::TarantoolWorld.None());
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

        internal static class DropWasmInterop
        {
            [DllImport("tarantool:tarantool/sequence", EntryPoint = "drop"), WasmImportLinkage]
            internal static extern void wasmImportDrop(int p0, nint p1);
        }

        public  static unsafe void Drop(global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.Sequence seq)
        {

            var retArea = stackalloc uint[14+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            DropWasmInterop.wasmImportDrop(seq.id, ptr);

            Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError> lifted18;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Ok(new global::TarantoolWorld.None());
                    break;
                }
                case 1: {

                    List<(string, string)>? lifted;

                    switch (new Span<byte>((void*)(ptr + 24), 1)[0]) {
                        case 0: {
                            lifted = null;
                            break;
                        }

                        case 1: {

                            var array = new List<(string, string)>(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)));
                            for (int index = 0; index < BitConverter.ToInt32(new Span<byte>((void*)(ptr + 32), 4)); ++index) {
                                nint basePtr7 = BitConverter.ToInt32(new Span<byte>((void*)(ptr + 28), 4)) + (index * 16);

                                array.Add((Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 4), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 8), 4)), BitConverter.ToInt32(new Span<byte>((void*)(basePtr7 + 12), 4)))));
                            }

                            lifted = array;
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 24), 1)[0]));
                    }

                    string? lifted12;

                    switch (new Span<byte>((void*)(ptr + 36), 1)[0]) {
                        case 0: {
                            lifted12 = null;
                            break;
                        }

                        case 1: {

                            lifted12 = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 40), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 44), 4)));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 36), 1)[0]));
                    }

                    uint? lifted17;

                    switch (new Span<byte>((void*)(ptr + 48), 1)[0]) {
                        case 0: {
                            lifted17 = null;
                            break;
                        }

                        case 1: {

                            lifted17 = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 52), 4))));
                            break;
                        }

                        default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 48), 1)[0]));
                    }

                    lifted18 = Result<None, global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>.Err(new global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError (
                    Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))), Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4)))), lifted, lifted12, lifted17));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }
            if (lifted18.IsOk)
            {
                var tmp = lifted18.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::TarantoolWorld.wit.imports.tarantool.tarantool.ITypes.BoxError>(lifted18.AsErr!, 0);
            }

        }

    }
}
