interface box {

    use types.{
        space,
        index,
        box-error,
        box-tuple,
    };

    schema-version: func() -> s64;
    space-by-name: func(name: string) -> result<space, box-error>;
    index-by-name: func(name: string, index-base: s32) -> result<index, box-error>;
    insert: func(space: space, tup: list<u8>) -> result<box-tuple, box-error>;
    replace: func(space: space, tup: list<u8>) -> result<box-tuple, box-error>;
    truncate: func(space: space) -> result<_, box-error>;
    delete: func(index: index, key: list<u8>) -> result<box-tuple, box-error>;
    update: func(index: index, key: list<u8>, ops: list<u8>) -> result<box-tuple, box-error>;
    upsert: func(index: index, tup: list<u8>, ops: list<u8>) -> result<box-tuple, box-error>;

}
