interface error {
        use types.{
                box-error,
                empty-result,
        };

        last: func() -> option<box-error>;
        clear: func();
        set: func(err: box-error);
        to-string: func(err: box-error) -> string;

        raise: func() -> empty-result;
        new: func(err: box-error) -> box-error;
        get-message: func(err: box-error) -> string;
        get-code: func(err: box-error) -> u32;
        get-type: func(err: box-error) -> string;
}
