interface sequence {
        use types.{
                sequence,
                s64-result,
                empty-result,
                sequence-options,
                sequence-result
        };

        next: func(seq: sequence) -> s64-result;
        current: func(seq: sequence) -> s64-result;
        set: func(seq: sequence, value: s64) -> empty-result;
        reset: func(seq: sequence) -> empty-result;
        create: func(name: string, opts: option<sequence-options>) -> sequence-result;
        alter: func(seq: sequence, opts: sequence-options) -> empty-result;
        drop: func(seq: sequence) -> empty-result;
}