package tarantool:tarantool;

world tarantool {
    import types;
    import key-def;
    import tuple-format;
    import %tuple;
    import error;
    import say;
    import txn;
    import box;
    import session;
    import sequence;
    import index;
}
