interface txn {

    use types.{
        box-error,
        txn-isolation-level,
    };

    txn-id: func() -> s64;
    txn-isolation: func() -> txn-isolation-level;
    txn: func() -> bool;
    begin: func() -> result<_, box-error>;
    commit: func() -> result<_, box-error>;
    rollback: func() -> result<_, box-error>;
    txn-set-isolation: func(isolation: txn-isolation-level) -> result<_, box-error>;
    txn-make-sync: func();

}
