interface txn {
        use types.{
                txn-isolation-level,
                empty-result
        };

        txn-id: func() -> s64;
        txn-isolation: func() -> txn-isolation-level;
        txn: func() -> bool;
        begin: func() -> empty-result;
        commit: func() -> empty-result;
        rollback: func() -> empty-result;
        txn-set-isolation: func(isolation: txn-isolation-level) -> empty-result;
        txn-make-sync: func();

}
