@since(version = 0.2.0)
/// Reads metrics maintained by the Tarantool instance.
interface metrics {

    /// Returns the current uptime of the instance in seconds.
    ///
    /// Corresponds to `box.info.uptime`.
    ///
    /// ### Returns
    /// - Uptime in seconds as a floating-point value (`f64`).
    @since(version = 0.2.0)
    uptime: func() -> f64;
}
