// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
#ifndef __BINDINGS_TARANTOOL_H
#define __BINDINGS_TARANTOOL_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct tarantool_string_t {
  uint8_t*ptr;
  size_t len;
} tarantool_string_t;

typedef uint8_t tarantool_tarantool_types_log_level_t;

#define TARANTOOL_TARANTOOL_TYPES_LOG_LEVEL_S_FATAL 0
#define TARANTOOL_TARANTOOL_TYPES_LOG_LEVEL_S_SYSERROR 1
#define TARANTOOL_TARANTOOL_TYPES_LOG_LEVEL_S_ERROR 2
#define TARANTOOL_TARANTOOL_TYPES_LOG_LEVEL_S_CRIT 3
#define TARANTOOL_TARANTOOL_TYPES_LOG_LEVEL_S_WARN 4
#define TARANTOOL_TARANTOOL_TYPES_LOG_LEVEL_S_INFO 5
#define TARANTOOL_TARANTOOL_TYPES_LOG_LEVEL_S_VERBOSE 6
#define TARANTOOL_TARANTOOL_TYPES_LOG_LEVEL_S_DEBUG 7

typedef uint8_t tarantool_tarantool_types_iterator_type_t;

#define TARANTOOL_TARANTOOL_TYPES_ITERATOR_TYPE_ITER_EQ 0
#define TARANTOOL_TARANTOOL_TYPES_ITERATOR_TYPE_ITER_REQ 1
#define TARANTOOL_TARANTOOL_TYPES_ITERATOR_TYPE_ITER_ALL 2
#define TARANTOOL_TARANTOOL_TYPES_ITERATOR_TYPE_ITER_LT 3
#define TARANTOOL_TARANTOOL_TYPES_ITERATOR_TYPE_ITER_LE 4
#define TARANTOOL_TARANTOOL_TYPES_ITERATOR_TYPE_ITER_GE 5
#define TARANTOOL_TARANTOOL_TYPES_ITERATOR_TYPE_ITER_GT 6
#define TARANTOOL_TARANTOOL_TYPES_ITERATOR_TYPE_ITER_BITS_ALL_SET 7
#define TARANTOOL_TARANTOOL_TYPES_ITERATOR_TYPE_ITER_BITS_ANY_SET 8
#define TARANTOOL_TARANTOOL_TYPES_ITERATOR_TYPE_ITER_BITS_ALL_NOT_SET 9
#define TARANTOOL_TARANTOOL_TYPES_ITERATOR_TYPE_ITER_OVERLAPS 10
#define TARANTOOL_TARANTOOL_TYPES_ITERATOR_TYPE_ITER_NEIGHBOR 11
#define TARANTOOL_TARANTOOL_TYPES_ITERATOR_TYPE_ITER_NP 12
#define TARANTOOL_TARANTOOL_TYPES_ITERATOR_TYPE_ITER_PP 13

typedef uint8_t tarantool_tarantool_types_txn_isolation_level_t;

// take isolation level from global default_isolation_level.
#define TARANTOOL_TARANTOOL_TYPES_TXN_ISOLATION_LEVEL_TXN_ISOLATION_DEFAULT 0
// allow to read committed, but not confirmed changes.
#define TARANTOOL_TARANTOOL_TYPES_TXN_ISOLATION_LEVEL_TXN_ISOLATION_READ_COMMITTED 1
// allow to read only confirmed changes.
#define TARANTOOL_TARANTOOL_TYPES_TXN_ISOLATION_LEVEL_TXN_ISOLATION_READ_CONFIRMED 2
// determine isolation level automatically.
#define TARANTOOL_TARANTOOL_TYPES_TXN_ISOLATION_LEVEL_TXN_ISOLATION_BEST_EFFORT 3
// allow to read only the changes confirmed on any cluster node.
#define TARANTOOL_TARANTOOL_TYPES_TXN_ISOLATION_LEVEL_TXN_ISOLATION_LINEARIZABLE 4

typedef uint8_t tarantool_tarantool_types_index_type_t;

#define TARANTOOL_TARANTOOL_TYPES_INDEX_TYPE_TREE 0
#define TARANTOOL_TARANTOOL_TYPES_INDEX_TYPE_HASH 1
#define TARANTOOL_TARANTOOL_TYPES_INDEX_TYPE_BITSET 2
#define TARANTOOL_TARANTOOL_TYPES_INDEX_TYPE_RTREE 3

typedef uint8_t tarantool_tarantool_types_key_part_flags_t;

#define TARANTOOL_TARANTOOL_TYPES_KEY_PART_FLAGS_IS_NULLABLE (1 << 0)
#define TARANTOOL_TARANTOOL_TYPES_KEY_PART_FLAGS_EXCLUDE_NULL (1 << 1)

typedef struct tarantool_tarantool_types_field_identifier_t {
  uint8_t tag;
  union {
    uint32_t     number;
    tarantool_string_t     name;
  } val;
} tarantool_tarantool_types_field_identifier_t;

#define TARANTOOL_TARANTOOL_TYPES_FIELD_IDENTIFIER_NUMBER 0
#define TARANTOOL_TARANTOOL_TYPES_FIELD_IDENTIFIER_NAME 1

typedef struct {
  bool is_some;
  tarantool_string_t val;
} tarantool_option_string_t;

typedef struct tarantool_tarantool_types_key_part_def_t {
  tarantool_tarantool_types_field_identifier_t   field;
  tarantool_string_t   field_type;
  tarantool_option_string_t   collation;
  tarantool_option_string_t   path;
  tarantool_tarantool_types_key_part_flags_t   flags;
} tarantool_tarantool_types_key_part_def_t;

typedef struct {
  tarantool_string_t f0;
  tarantool_string_t f1;
} tarantool_tuple2_string_string_t;

typedef struct {
  tarantool_tuple2_string_string_t *ptr;
  size_t len;
} tarantool_list_tuple2_string_string_t;

typedef struct {
  bool is_some;
  tarantool_list_tuple2_string_string_t val;
} tarantool_option_list_tuple2_string_string_t;

typedef struct {
  bool is_some;
  uint32_t val;
} tarantool_option_u32_t;

typedef struct tarantool_tarantool_types_box_error_t {
  tarantool_string_t   message;
  tarantool_string_t   type;
  uint32_t   code;
  tarantool_option_list_tuple2_string_string_t   payload;
  tarantool_option_string_t   file;
  tarantool_option_u32_t   line;
} tarantool_tarantool_types_box_error_t;

typedef struct tarantool_tarantool_types_index_t {
  int32_t   id;
  int32_t   space_id;
  int32_t   index_base;
} tarantool_tarantool_types_index_t;

typedef struct tarantool_tarantool_types_sequence_t {
  int32_t   id;
} tarantool_tarantool_types_sequence_t;

typedef struct tarantool_tarantool_types_space_t {
  int32_t   id;
} tarantool_tarantool_types_space_t;

typedef struct tarantool_tarantool_types_sequence_options_t {
  int64_t   start;
  int64_t   increment;
  int64_t   min;
  int64_t   max;
  bool   cycle;
} tarantool_tarantool_types_sequence_options_t;

typedef struct tarantool_tarantool_types_peer_t {
  tarantool_string_t   host;
  uint32_t   port;
} tarantool_tarantool_types_peer_t;

typedef struct tarantool_tarantool_types_session_t {
  int64_t   id;
} tarantool_tarantool_types_session_t;

typedef struct {
  bool is_some;
  tarantool_tarantool_types_iterator_type_t val;
} tarantool_tarantool_types_option_iterator_type_t;

typedef struct {
  bool is_some;
  int64_t val;
} tarantool_option_s64_t;

typedef struct {
  bool is_some;
  bool val;
} tarantool_option_bool_t;

typedef struct tarantool_tarantool_types_select_opts_t {
  tarantool_tarantool_types_option_iterator_type_t   iterator;
  tarantool_option_u32_t   limit;
  tarantool_option_u32_t   offset;
  tarantool_option_s64_t   after;
  tarantool_option_bool_t   fetch_pos;
} tarantool_tarantool_types_select_opts_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} tarantool_list_u8_t;

typedef struct {
  bool is_some;
  tarantool_list_u8_t val;
} tarantool_option_list_u8_t;

typedef struct tarantool_tarantool_types_pairs_opts_t {
  tarantool_option_list_u8_t   key;
  tarantool_tarantool_types_option_iterator_type_t   iterator;
  tarantool_option_s64_t   after;
} tarantool_tarantool_types_pairs_opts_t;

typedef struct tarantool_tarantool_types_update_op_t {
  uint32_t   field_no;
  tarantool_string_t   op;
  tarantool_list_u8_t   operand;
} tarantool_tarantool_types_update_op_t;

typedef struct tarantool_tarantool_types_index_stat_t {
  int64_t   bsize;
  int64_t   len;
} tarantool_tarantool_types_index_stat_t;

typedef uint64_t tarantool_tarantool_types_box_tuple_t;

typedef uint64_t tarantool_tarantool_types_tuple_field_t;

typedef uint64_t tarantool_tarantool_types_tuple_format_t;

typedef struct tarantool_tarantool_types_tuple_list_t {
  tarantool_tarantool_types_box_tuple_t   *ptr;
  size_t len;
} tarantool_tarantool_types_tuple_list_t;

typedef uint64_t tarantool_tarantool_types_key_def_t;

typedef struct tarantool_tarantool_types_key_def_list_t {
  tarantool_tarantool_types_key_def_t   *ptr;
  size_t len;
} tarantool_tarantool_types_key_def_list_t;

typedef struct tarantool_tarantool_types_key_part_def_list_t {
  tarantool_tarantool_types_key_part_def_t   *ptr;
  size_t len;
} tarantool_tarantool_types_key_part_def_list_t;

typedef struct tarantool_tarantool_types_storage_t {
  tarantool_tuple2_string_string_t   *ptr;
  size_t len;
} tarantool_tarantool_types_storage_t;

typedef struct tarantool_tarantool_types_own_iterator_t {
  int32_t __handle;
} tarantool_tarantool_types_own_iterator_t;

typedef struct tarantool_tarantool_types_borrow_iterator_t {
  int32_t __handle;
} tarantool_tarantool_types_borrow_iterator_t;

typedef struct tarantool_tarantool_types_own_tuple_iterator_t {
  int32_t __handle;
} tarantool_tarantool_types_own_tuple_iterator_t;

typedef struct tarantool_tarantool_types_borrow_tuple_iterator_t {
  int32_t __handle;
} tarantool_tarantool_types_borrow_tuple_iterator_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_types_own_iterator_t ok;
    tarantool_tarantool_types_box_error_t err;
  } val;
} tarantool_tarantool_types_result_own_iterator_box_error_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_types_box_tuple_t ok;
    tarantool_tarantool_types_box_error_t err;
  } val;
} tarantool_tarantool_types_result_box_tuple_box_error_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_types_own_tuple_iterator_t ok;
    tarantool_tarantool_types_box_error_t err;
  } val;
} tarantool_tarantool_types_result_own_tuple_iterator_box_error_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_types_tuple_field_t ok;
    tarantool_tarantool_types_box_error_t err;
  } val;
} tarantool_tarantool_types_result_tuple_field_box_error_t;

typedef tarantool_tarantool_types_box_error_t tarantool_tarantool_key_def_box_error_t;

typedef tarantool_tarantool_types_box_tuple_t tarantool_tarantool_key_def_box_tuple_t;

typedef tarantool_tarantool_types_key_def_t tarantool_tarantool_key_def_key_def_t;

typedef tarantool_tarantool_types_key_part_def_list_t tarantool_tarantool_key_def_key_part_def_list_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_key_def_key_def_t ok;
    tarantool_tarantool_key_def_box_error_t err;
  } val;
} tarantool_tarantool_key_def_result_key_def_box_error_t;

typedef struct {
  bool f0;
  uint32_t f1;
} tarantool_tuple2_bool_u32_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tuple2_bool_u32_t ok;
    tarantool_tarantool_key_def_box_error_t err;
  } val;
} tarantool_tarantool_key_def_result_tuple2_bool_u32_box_error_t;

typedef struct {
  bool is_err;
  union {
    uint32_t ok;
    tarantool_tarantool_key_def_box_error_t err;
  } val;
} tarantool_tarantool_key_def_result_u32_box_error_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_key_def_key_part_def_list_t ok;
    tarantool_tarantool_key_def_box_error_t err;
  } val;
} tarantool_tarantool_key_def_result_key_part_def_list_box_error_t;

typedef tarantool_tarantool_types_key_def_list_t tarantool_tarantool_tuple_format_key_def_list_t;

typedef tarantool_tarantool_types_box_error_t tarantool_tarantool_tuple_format_box_error_t;

typedef tarantool_tarantool_types_tuple_format_t tarantool_tarantool_tuple_format_tuple_format_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_tuple_format_tuple_format_t ok;
    tarantool_tarantool_tuple_format_box_error_t err;
  } val;
} tarantool_tarantool_tuple_format_result_tuple_format_box_error_t;

typedef tarantool_tarantool_types_box_error_t tarantool_tarantool_tuple_box_error_t;

typedef tarantool_tarantool_types_box_tuple_t tarantool_tarantool_tuple_box_tuple_t;

typedef tarantool_tarantool_types_tuple_field_t tarantool_tarantool_tuple_tuple_field_t;

typedef tarantool_tarantool_types_tuple_format_t tarantool_tarantool_tuple_tuple_format_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_tuple_box_tuple_t ok;
    tarantool_tarantool_tuple_box_error_t err;
  } val;
} tarantool_tarantool_tuple_result_box_tuple_box_error_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_tuple_tuple_field_t ok;
    tarantool_tarantool_tuple_box_error_t err;
  } val;
} tarantool_tarantool_tuple_result_tuple_field_box_error_t;

typedef tarantool_tarantool_types_box_error_t tarantool_tarantool_error_box_error_t;

typedef struct {
  bool is_some;
  tarantool_tarantool_error_box_error_t val;
} tarantool_tarantool_error_option_box_error_t;

typedef tarantool_tarantool_types_log_level_t tarantool_tarantool_say_log_level_t;

typedef tarantool_tarantool_types_box_error_t tarantool_tarantool_txn_box_error_t;

typedef tarantool_tarantool_types_txn_isolation_level_t tarantool_tarantool_txn_txn_isolation_level_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_txn_box_error_t err;
  } val;
} tarantool_tarantool_txn_result_void_box_error_t;

typedef tarantool_tarantool_types_space_t tarantool_tarantool_box_space_t;

typedef tarantool_tarantool_types_index_t tarantool_tarantool_box_index_t;

typedef tarantool_tarantool_types_box_error_t tarantool_tarantool_box_box_error_t;

typedef tarantool_tarantool_types_box_tuple_t tarantool_tarantool_box_box_tuple_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_box_space_t ok;
    tarantool_tarantool_box_box_error_t err;
  } val;
} tarantool_tarantool_box_result_space_box_error_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_box_index_t ok;
    tarantool_tarantool_box_box_error_t err;
  } val;
} tarantool_tarantool_box_result_index_box_error_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_box_box_tuple_t ok;
    tarantool_tarantool_box_box_error_t err;
  } val;
} tarantool_tarantool_box_result_box_tuple_box_error_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_box_box_error_t err;
  } val;
} tarantool_tarantool_box_result_void_box_error_t;

typedef tarantool_tarantool_types_box_error_t tarantool_tarantool_session_box_error_t;

typedef tarantool_tarantool_types_session_t tarantool_tarantool_session_session_t;

typedef tarantool_tarantool_types_storage_t tarantool_tarantool_session_storage_t;

typedef tarantool_tarantool_types_peer_t tarantool_tarantool_session_peer_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_session_box_error_t err;
  } val;
} tarantool_tarantool_session_result_void_box_error_t;

typedef struct {
  bool is_err;
  union {
    int64_t ok;
    tarantool_tarantool_session_box_error_t err;
  } val;
} tarantool_tarantool_session_result_s64_box_error_t;

typedef struct {
  bool is_err;
  union {
    bool ok;
    tarantool_tarantool_session_box_error_t err;
  } val;
} tarantool_tarantool_session_result_bool_box_error_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_session_peer_t ok;
    tarantool_tarantool_session_box_error_t err;
  } val;
} tarantool_tarantool_session_result_peer_box_error_t;

typedef struct {
  bool is_err;
  union {
    tarantool_string_t ok;
    tarantool_tarantool_session_box_error_t err;
  } val;
} tarantool_tarantool_session_result_string_box_error_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_session_storage_t ok;
    tarantool_tarantool_session_box_error_t err;
  } val;
} tarantool_tarantool_session_result_storage_box_error_t;

typedef tarantool_tarantool_types_sequence_t tarantool_tarantool_sequence_sequence_t;

typedef tarantool_tarantool_types_box_error_t tarantool_tarantool_sequence_box_error_t;

typedef tarantool_tarantool_types_sequence_options_t tarantool_tarantool_sequence_sequence_options_t;

typedef struct {
  bool is_err;
  union {
    int64_t ok;
    tarantool_tarantool_sequence_box_error_t err;
  } val;
} tarantool_tarantool_sequence_result_s64_box_error_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_sequence_box_error_t err;
  } val;
} tarantool_tarantool_sequence_result_void_box_error_t;

typedef struct {
  bool is_some;
  tarantool_tarantool_sequence_sequence_options_t val;
} tarantool_tarantool_sequence_option_sequence_options_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_sequence_sequence_t ok;
    tarantool_tarantool_sequence_box_error_t err;
  } val;
} tarantool_tarantool_sequence_result_sequence_box_error_t;

typedef tarantool_tarantool_types_index_t tarantool_tarantool_index_index_t;

typedef tarantool_tarantool_types_box_error_t tarantool_tarantool_index_box_error_t;

typedef tarantool_tarantool_types_box_tuple_t tarantool_tarantool_index_box_tuple_t;

typedef tarantool_tarantool_types_iterator_type_t tarantool_tarantool_index_iterator_type_t;

typedef tarantool_tarantool_types_key_part_def_t tarantool_tarantool_index_key_part_def_t;

typedef tarantool_tarantool_types_key_part_def_list_t tarantool_tarantool_index_key_part_def_list_t;

typedef tarantool_tarantool_types_update_op_t tarantool_tarantool_index_update_op_t;

typedef tarantool_tarantool_types_tuple_list_t tarantool_tarantool_index_tuple_list_t;

typedef tarantool_tarantool_types_index_type_t tarantool_tarantool_index_index_type_t;

typedef tarantool_tarantool_types_index_stat_t tarantool_tarantool_index_index_stat_t;

typedef tarantool_tarantool_types_pairs_opts_t tarantool_tarantool_index_pairs_opts_t;

typedef tarantool_tarantool_types_select_opts_t tarantool_tarantool_index_select_opts_t;

typedef struct {
  bool is_err;
  union {
    int64_t ok;
    tarantool_tarantool_index_box_error_t err;
  } val;
} tarantool_tarantool_index_result_s64_box_error_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_index_box_tuple_t ok;
    tarantool_tarantool_index_box_error_t err;
  } val;
} tarantool_tarantool_index_result_box_tuple_box_error_t;

typedef struct {
  bool is_err;
  union {
    bool ok;
    tarantool_tarantool_index_box_error_t err;
  } val;
} tarantool_tarantool_index_result_bool_box_error_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_index_index_type_t ok;
    tarantool_tarantool_index_box_error_t err;
  } val;
} tarantool_tarantool_index_result_index_type_box_error_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_index_key_part_def_list_t ok;
    tarantool_tarantool_index_box_error_t err;
  } val;
} tarantool_tarantool_index_result_key_part_def_list_box_error_t;

typedef tarantool_tarantool_types_own_iterator_t tarantool_tarantool_index_own_iterator_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_index_own_iterator_t ok;
    tarantool_tarantool_index_box_error_t err;
  } val;
} tarantool_tarantool_index_result_own_iterator_box_error_t;

typedef struct {
  tarantool_tarantool_index_box_tuple_t *ptr;
  size_t len;
} tarantool_list_box_tuple_t;

typedef struct {
  bool is_err;
  union {
    tarantool_list_box_tuple_t ok;
    tarantool_tarantool_index_box_error_t err;
  } val;
} tarantool_tarantool_index_result_list_box_tuple_box_error_t;

typedef struct {
  tarantool_tarantool_index_update_op_t *ptr;
  size_t len;
} tarantool_tarantool_index_list_update_op_t;

typedef struct {
  tarantool_tarantool_index_key_part_def_t *ptr;
  size_t len;
} tarantool_tarantool_index_list_key_part_def_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_index_box_error_t err;
  } val;
} tarantool_tarantool_index_result_void_box_error_t;

typedef struct {
  bool is_err;
  union {
    tarantool_tarantool_index_index_stat_t ok;
    tarantool_tarantool_index_box_error_t err;
  } val;
} tarantool_tarantool_index_result_index_stat_box_error_t;

// Imported Functions from `tarantool:tarantool/types`
extern void tarantool_tarantool_types_static_iterator_new_iterator(tarantool_tarantool_types_index_t *index, tarantool_tarantool_types_iterator_type_t iterator_type, tarantool_list_u8_t *key, tarantool_tarantool_types_result_own_iterator_box_error_t *ret);
extern void tarantool_tarantool_types_method_iterator_next(tarantool_tarantool_types_borrow_iterator_t self, tarantool_tarantool_types_result_box_tuple_box_error_t *ret);
extern void tarantool_tarantool_types_static_tuple_iterator_new_tuple_iterator(tarantool_tarantool_types_box_tuple_t tuple, tarantool_tarantool_types_result_own_tuple_iterator_box_error_t *ret);
extern uint32_t tarantool_tarantool_types_method_tuple_iterator_position(tarantool_tarantool_types_borrow_tuple_iterator_t self);
extern void tarantool_tarantool_types_method_tuple_iterator_rewind(tarantool_tarantool_types_borrow_tuple_iterator_t self);
extern void tarantool_tarantool_types_method_tuple_iterator_seek(tarantool_tarantool_types_borrow_tuple_iterator_t self, uint32_t pos, tarantool_tarantool_types_result_tuple_field_box_error_t *ret);
extern void tarantool_tarantool_types_method_tuple_iterator_next(tarantool_tarantool_types_borrow_tuple_iterator_t self, tarantool_tarantool_types_result_tuple_field_box_error_t *ret);

// Imported Functions from `tarantool:tarantool/key-def`
extern void tarantool_tarantool_key_def_new(tarantool_tarantool_key_def_key_part_def_list_t *parts, tarantool_tarantool_key_def_result_key_def_box_error_t *ret);
extern void tarantool_tarantool_key_def_merge(tarantool_tarantool_key_def_key_def_t left, tarantool_tarantool_key_def_key_def_t right, tarantool_tarantool_key_def_result_key_def_box_error_t *ret);
extern void tarantool_tarantool_key_def_validate_key(tarantool_tarantool_key_def_key_def_t key_def, tarantool_list_u8_t *key, tarantool_tarantool_key_def_result_tuple2_bool_u32_box_error_t *ret);
extern void tarantool_tarantool_key_def_validate_full_key(tarantool_tarantool_key_def_key_def_t key_def, tarantool_list_u8_t *key, tarantool_tarantool_key_def_result_tuple2_bool_u32_box_error_t *ret);
extern int32_t tarantool_tarantool_key_def_compare(tarantool_tarantool_key_def_key_def_t key_def, tarantool_tarantool_key_def_box_tuple_t left, tarantool_tarantool_key_def_box_tuple_t right);
extern int32_t tarantool_tarantool_key_def_compare_keys(tarantool_tarantool_key_def_key_def_t key_def, tarantool_tarantool_key_def_key_def_t left, tarantool_tarantool_key_def_key_def_t right);
extern tarantool_tarantool_key_def_box_tuple_t tarantool_tarantool_key_def_extract_key(tarantool_tarantool_key_def_key_def_t key_def, tarantool_tarantool_key_def_box_tuple_t tuple);
extern void tarantool_tarantool_key_def_part_count(tarantool_tarantool_key_def_key_def_t key_def, tarantool_tarantool_key_def_result_u32_box_error_t *ret);
extern bool tarantool_tarantool_key_def_validate_tuple(tarantool_tarantool_key_def_key_def_t key_def, tarantool_tarantool_key_def_box_tuple_t tuple);
extern void tarantool_tarantool_key_def_dup(tarantool_tarantool_key_def_key_def_t key_def, tarantool_tarantool_key_def_result_key_def_box_error_t *ret);
extern void tarantool_tarantool_key_def_delete(tarantool_tarantool_key_def_key_def_t key_def);
extern void tarantool_tarantool_key_def_dump_parts(tarantool_tarantool_key_def_key_def_t key_def, tarantool_tarantool_key_def_result_key_part_def_list_box_error_t *ret);

// Imported Functions from `tarantool:tarantool/tuple-format`
extern tarantool_tarantool_tuple_format_tuple_format_t tarantool_tarantool_tuple_format_default(void);
extern void tarantool_tarantool_tuple_format_new(tarantool_tarantool_tuple_format_key_def_list_t *key_defs, tarantool_tarantool_tuple_format_result_tuple_format_box_error_t *ret);
extern void tarantool_tarantool_tuple_format_ref(tarantool_tarantool_tuple_format_tuple_format_t tf);
extern void tarantool_tarantool_tuple_format_unref(tarantool_tarantool_tuple_format_tuple_format_t tf);

// Imported Functions from `tarantool:tarantool/tuple`
extern void tarantool_tarantool_tuple_new(tarantool_tarantool_tuple_tuple_format_t format, tarantool_list_u8_t *data, tarantool_tarantool_tuple_result_box_tuple_box_error_t *ret);
extern int32_t tarantool_tarantool_tuple_ref(tarantool_tarantool_tuple_box_tuple_t t);
extern void tarantool_tarantool_tuple_unref(tarantool_tarantool_tuple_box_tuple_t t);
extern uint32_t tarantool_tarantool_tuple_field_count(tarantool_tarantool_tuple_box_tuple_t t);
extern uint64_t tarantool_tarantool_tuple_bsize(tarantool_tarantool_tuple_box_tuple_t t);
extern void tarantool_tarantool_tuple_to_buf(tarantool_tarantool_tuple_box_tuple_t t, tarantool_list_u8_t *ret);
extern tarantool_tarantool_tuple_tuple_format_t tarantool_tarantool_tuple_format(tarantool_tarantool_tuple_box_tuple_t t);
extern void tarantool_tarantool_tuple_field(tarantool_tarantool_tuple_box_tuple_t t, uint32_t idx, tarantool_tarantool_tuple_result_tuple_field_box_error_t *ret);
extern void tarantool_tarantool_tuple_field_by_path(tarantool_string_t *path, int32_t index_base, tarantool_tarantool_tuple_result_tuple_field_box_error_t *ret);
extern void tarantool_tarantool_tuple_update(tarantool_tarantool_tuple_box_tuple_t t, tarantool_list_u8_t *expr, tarantool_tarantool_tuple_result_box_tuple_box_error_t *ret);
extern void tarantool_tarantool_tuple_upsert(tarantool_tarantool_tuple_box_tuple_t t, tarantool_list_u8_t *expr, tarantool_tarantool_tuple_result_box_tuple_box_error_t *ret);
extern bool tarantool_tarantool_tuple_validate(tarantool_tarantool_tuple_box_tuple_t t, tarantool_tarantool_tuple_tuple_format_t format);

// Imported Functions from `tarantool:tarantool/error`
extern void tarantool_tarantool_error_new(tarantool_string_t *message, tarantool_string_t *type, uint32_t code, tarantool_tarantool_error_box_error_t *ret);
extern void tarantool_tarantool_error_set(tarantool_tarantool_error_box_error_t *err_);
extern void tarantool_tarantool_error_last(tarantool_tarantool_error_option_box_error_t *ret);
extern void tarantool_tarantool_error_clear(void);
extern void tarantool_tarantool_error_to_string(tarantool_tarantool_error_box_error_t *err_, tarantool_string_t *ret);

// Imported Functions from `tarantool:tarantool/say`
extern void tarantool_tarantool_say_say(tarantool_tarantool_say_log_level_t level, tarantool_string_t *msg);
extern void tarantool_tarantool_say_say_error(tarantool_string_t *msg);
extern void tarantool_tarantool_say_say_crit(tarantool_string_t *msg);
extern void tarantool_tarantool_say_say_warn(tarantool_string_t *msg);
extern void tarantool_tarantool_say_say_info(tarantool_string_t *msg);
extern void tarantool_tarantool_say_say_verbose(tarantool_string_t *msg);
extern void tarantool_tarantool_say_say_debug(tarantool_string_t *msg);
extern void tarantool_tarantool_say_say_syserror(tarantool_string_t *msg);

// Imported Functions from `tarantool:tarantool/txn`
extern int64_t tarantool_tarantool_txn_txn_id(void);
extern tarantool_tarantool_txn_txn_isolation_level_t tarantool_tarantool_txn_txn_isolation(void);
extern bool tarantool_tarantool_txn_txn(void);
extern void tarantool_tarantool_txn_begin(tarantool_tarantool_txn_result_void_box_error_t *ret);
extern void tarantool_tarantool_txn_commit(tarantool_tarantool_txn_result_void_box_error_t *ret);
extern void tarantool_tarantool_txn_rollback(tarantool_tarantool_txn_result_void_box_error_t *ret);
extern void tarantool_tarantool_txn_txn_set_isolation(tarantool_tarantool_txn_txn_isolation_level_t isolation, tarantool_tarantool_txn_result_void_box_error_t *ret);
extern void tarantool_tarantool_txn_txn_make_sync(void);

// Imported Functions from `tarantool:tarantool/box`
extern int64_t tarantool_tarantool_box_schema_version(void);
extern void tarantool_tarantool_box_space_by_name(tarantool_string_t *name, tarantool_tarantool_box_result_space_box_error_t *ret);
extern void tarantool_tarantool_box_index_by_name(tarantool_string_t *name, int32_t index_base, tarantool_tarantool_box_result_index_box_error_t *ret);
extern void tarantool_tarantool_box_insert(tarantool_tarantool_box_space_t *space, tarantool_list_u8_t *tup, tarantool_tarantool_box_result_box_tuple_box_error_t *ret);
extern void tarantool_tarantool_box_replace(tarantool_tarantool_box_space_t *space, tarantool_list_u8_t *tup, tarantool_tarantool_box_result_box_tuple_box_error_t *ret);
extern void tarantool_tarantool_box_truncate(tarantool_tarantool_box_space_t *space, tarantool_tarantool_box_result_void_box_error_t *ret);
extern void tarantool_tarantool_box_delete(tarantool_tarantool_box_index_t *index, tarantool_list_u8_t *key, tarantool_tarantool_box_result_box_tuple_box_error_t *ret);
extern void tarantool_tarantool_box_update(tarantool_tarantool_box_index_t *index, tarantool_list_u8_t *key, tarantool_list_u8_t *ops, tarantool_tarantool_box_result_box_tuple_box_error_t *ret);
extern void tarantool_tarantool_box_upsert(tarantool_tarantool_box_index_t *index, tarantool_list_u8_t *tup, tarantool_list_u8_t *ops, tarantool_tarantool_box_result_box_tuple_box_error_t *ret);

// Imported Functions from `tarantool:tarantool/session`
extern void tarantool_tarantool_session_current(tarantool_tarantool_session_session_t *ret);
extern void tarantool_tarantool_session_iproto_send(tarantool_tarantool_session_session_t *session, tarantool_list_u8_t *header, tarantool_list_u8_t *body, tarantool_tarantool_session_result_void_box_error_t *ret);
extern void tarantool_tarantool_session_id(tarantool_tarantool_session_session_t *session, tarantool_tarantool_session_result_s64_box_error_t *ret);
extern void tarantool_tarantool_session_exists(tarantool_tarantool_session_result_bool_box_error_t *ret);
extern void tarantool_tarantool_session_get_peer(tarantool_tarantool_session_session_t *session, tarantool_tarantool_session_result_peer_box_error_t *ret);
extern void tarantool_tarantool_session_sync(tarantool_tarantool_session_result_s64_box_error_t *ret);
extern void tarantool_tarantool_session_user(tarantool_tarantool_session_result_string_box_error_t *ret);
extern void tarantool_tarantool_session_type(tarantool_tarantool_session_session_t *session, tarantool_tarantool_session_result_string_box_error_t *ret);
extern void tarantool_tarantool_session_su(tarantool_tarantool_session_session_t *session, tarantool_string_t *user, tarantool_tarantool_session_result_void_box_error_t *ret);
extern void tarantool_tarantool_session_uid(tarantool_tarantool_session_session_t *session, tarantool_tarantool_session_result_s64_box_error_t *ret);
extern void tarantool_tarantool_session_euid(tarantool_tarantool_session_session_t *session, tarantool_tarantool_session_result_s64_box_error_t *ret);
extern void tarantool_tarantool_session_get_storage(tarantool_tarantool_session_session_t *session, tarantool_tarantool_session_result_storage_box_error_t *ret);

// Imported Functions from `tarantool:tarantool/sequence`
extern void tarantool_tarantool_sequence_next(tarantool_tarantool_sequence_sequence_t *seq, tarantool_tarantool_sequence_result_s64_box_error_t *ret);
extern void tarantool_tarantool_sequence_current(tarantool_tarantool_sequence_sequence_t *seq, tarantool_tarantool_sequence_result_s64_box_error_t *ret);
extern void tarantool_tarantool_sequence_set(tarantool_tarantool_sequence_sequence_t *seq, int64_t value, tarantool_tarantool_sequence_result_void_box_error_t *ret);
extern void tarantool_tarantool_sequence_reset(tarantool_tarantool_sequence_sequence_t *seq, tarantool_tarantool_sequence_result_void_box_error_t *ret);
extern void tarantool_tarantool_sequence_create(tarantool_string_t *name, tarantool_tarantool_sequence_option_sequence_options_t *opts, tarantool_tarantool_sequence_result_sequence_box_error_t *ret);
extern void tarantool_tarantool_sequence_alter(tarantool_tarantool_sequence_sequence_t *seq, tarantool_tarantool_sequence_sequence_options_t *opts, tarantool_tarantool_sequence_result_void_box_error_t *ret);
extern void tarantool_tarantool_sequence_drop(tarantool_tarantool_sequence_sequence_t *seq, tarantool_tarantool_sequence_result_void_box_error_t *ret);

// Imported Functions from `tarantool:tarantool/index`
extern void tarantool_tarantool_index_len(tarantool_tarantool_index_index_t *index, tarantool_tarantool_index_result_s64_box_error_t *ret);
extern void tarantool_tarantool_index_bsize(tarantool_tarantool_index_index_t *index, tarantool_tarantool_index_result_s64_box_error_t *ret);
extern void tarantool_tarantool_index_random(tarantool_tarantool_index_index_t *index, uint32_t rnd, tarantool_tarantool_index_result_box_tuple_box_error_t *ret);
extern void tarantool_tarantool_index_get(tarantool_tarantool_index_index_t *index, tarantool_list_u8_t *key, tarantool_tarantool_index_result_box_tuple_box_error_t *ret);
extern void tarantool_tarantool_index_min(tarantool_tarantool_index_index_t *index, tarantool_list_u8_t *key, tarantool_tarantool_index_result_box_tuple_box_error_t *ret);
extern void tarantool_tarantool_index_max(tarantool_tarantool_index_index_t *index, tarantool_list_u8_t *key, tarantool_tarantool_index_result_box_tuple_box_error_t *ret);
extern void tarantool_tarantool_index_count(tarantool_tarantool_index_iterator_type_t iter_type, tarantool_list_u8_t *key, tarantool_tarantool_index_result_s64_box_error_t *ret);
extern void tarantool_tarantool_index_unique(tarantool_tarantool_index_index_t *index, tarantool_tarantool_index_result_bool_box_error_t *ret);
extern void tarantool_tarantool_index_get_type(tarantool_tarantool_index_index_t *index, tarantool_tarantool_index_result_index_type_box_error_t *ret);
extern void tarantool_tarantool_index_parts(tarantool_tarantool_index_index_t *index, tarantool_tarantool_index_result_key_part_def_list_box_error_t *ret);
extern void tarantool_tarantool_index_pairs(tarantool_tarantool_index_index_t *index, tarantool_tarantool_index_pairs_opts_t *opts, tarantool_tarantool_index_result_own_iterator_box_error_t *ret);
extern void tarantool_tarantool_index_select(tarantool_tarantool_index_index_t *index, tarantool_list_u8_t *key, tarantool_tarantool_index_select_opts_t *opts, tarantool_tarantool_index_result_list_box_tuple_box_error_t *ret);
extern void tarantool_tarantool_index_update(tarantool_tarantool_index_index_t *index, tarantool_list_u8_t *key, tarantool_tarantool_index_list_update_op_t *ops, tarantool_tarantool_index_result_box_tuple_box_error_t *ret);
extern void tarantool_tarantool_index_delete(tarantool_tarantool_index_index_t *index, tarantool_list_u8_t *key, tarantool_tarantool_index_result_box_tuple_box_error_t *ret);
extern void tarantool_tarantool_index_alter(tarantool_tarantool_index_index_t *index, bool unique, tarantool_tarantool_index_list_key_part_def_t *parts, tarantool_tarantool_index_result_void_box_error_t *ret);
extern void tarantool_tarantool_index_drop(tarantool_tarantool_index_index_t *index, tarantool_tarantool_index_result_void_box_error_t *ret);
extern void tarantool_tarantool_index_rename(tarantool_tarantool_index_index_t *index, tarantool_string_t *new_name, tarantool_tarantool_index_result_void_box_error_t *ret);
extern void tarantool_tarantool_index_stat(tarantool_tarantool_index_index_t *index, tarantool_tarantool_index_result_index_stat_box_error_t *ret);
extern void tarantool_tarantool_index_compact(tarantool_tarantool_index_index_t *index, tarantool_tarantool_index_result_void_box_error_t *ret);
extern void tarantool_tarantool_index_tuple_pos(tarantool_tarantool_index_index_t *index, tarantool_list_u8_t *key, tarantool_tarantool_index_result_s64_box_error_t *ret);

// Helper Functions

void tarantool_tarantool_types_field_identifier_free(tarantool_tarantool_types_field_identifier_t *ptr);

void tarantool_option_string_free(tarantool_option_string_t *ptr);

void tarantool_tarantool_types_key_part_def_free(tarantool_tarantool_types_key_part_def_t *ptr);

void tarantool_tuple2_string_string_free(tarantool_tuple2_string_string_t *ptr);

void tarantool_list_tuple2_string_string_free(tarantool_list_tuple2_string_string_t *ptr);

void tarantool_option_list_tuple2_string_string_free(tarantool_option_list_tuple2_string_string_t *ptr);

void tarantool_option_u32_free(tarantool_option_u32_t *ptr);

void tarantool_tarantool_types_box_error_free(tarantool_tarantool_types_box_error_t *ptr);

void tarantool_tarantool_types_peer_free(tarantool_tarantool_types_peer_t *ptr);

void tarantool_tarantool_types_option_iterator_type_free(tarantool_tarantool_types_option_iterator_type_t *ptr);

void tarantool_option_s64_free(tarantool_option_s64_t *ptr);

void tarantool_option_bool_free(tarantool_option_bool_t *ptr);

void tarantool_tarantool_types_select_opts_free(tarantool_tarantool_types_select_opts_t *ptr);

void tarantool_list_u8_free(tarantool_list_u8_t *ptr);

void tarantool_option_list_u8_free(tarantool_option_list_u8_t *ptr);

void tarantool_tarantool_types_pairs_opts_free(tarantool_tarantool_types_pairs_opts_t *ptr);

void tarantool_tarantool_types_update_op_free(tarantool_tarantool_types_update_op_t *ptr);

void tarantool_tarantool_types_tuple_list_free(tarantool_tarantool_types_tuple_list_t *ptr);

void tarantool_tarantool_types_key_def_list_free(tarantool_tarantool_types_key_def_list_t *ptr);

void tarantool_tarantool_types_key_part_def_list_free(tarantool_tarantool_types_key_part_def_list_t *ptr);

void tarantool_tarantool_types_storage_free(tarantool_tarantool_types_storage_t *ptr);

extern void tarantool_tarantool_types_iterator_drop_own(tarantool_tarantool_types_own_iterator_t handle);

extern tarantool_tarantool_types_borrow_iterator_t tarantool_tarantool_types_borrow_iterator(tarantool_tarantool_types_own_iterator_t handle);

extern void tarantool_tarantool_types_tuple_iterator_drop_own(tarantool_tarantool_types_own_tuple_iterator_t handle);

extern tarantool_tarantool_types_borrow_tuple_iterator_t tarantool_tarantool_types_borrow_tuple_iterator(tarantool_tarantool_types_own_tuple_iterator_t handle);

void tarantool_tarantool_types_result_own_iterator_box_error_free(tarantool_tarantool_types_result_own_iterator_box_error_t *ptr);

void tarantool_tarantool_types_result_box_tuple_box_error_free(tarantool_tarantool_types_result_box_tuple_box_error_t *ptr);

void tarantool_tarantool_types_result_own_tuple_iterator_box_error_free(tarantool_tarantool_types_result_own_tuple_iterator_box_error_t *ptr);

void tarantool_tarantool_types_result_tuple_field_box_error_free(tarantool_tarantool_types_result_tuple_field_box_error_t *ptr);

void tarantool_tarantool_key_def_box_error_free(tarantool_tarantool_key_def_box_error_t *ptr);

void tarantool_tarantool_key_def_key_part_def_list_free(tarantool_tarantool_key_def_key_part_def_list_t *ptr);

void tarantool_tarantool_key_def_result_key_def_box_error_free(tarantool_tarantool_key_def_result_key_def_box_error_t *ptr);

void tarantool_tarantool_key_def_result_tuple2_bool_u32_box_error_free(tarantool_tarantool_key_def_result_tuple2_bool_u32_box_error_t *ptr);

void tarantool_tarantool_key_def_result_u32_box_error_free(tarantool_tarantool_key_def_result_u32_box_error_t *ptr);

void tarantool_tarantool_key_def_result_key_part_def_list_box_error_free(tarantool_tarantool_key_def_result_key_part_def_list_box_error_t *ptr);

void tarantool_tarantool_tuple_format_key_def_list_free(tarantool_tarantool_tuple_format_key_def_list_t *ptr);

void tarantool_tarantool_tuple_format_box_error_free(tarantool_tarantool_tuple_format_box_error_t *ptr);

void tarantool_tarantool_tuple_format_result_tuple_format_box_error_free(tarantool_tarantool_tuple_format_result_tuple_format_box_error_t *ptr);

void tarantool_tarantool_tuple_box_error_free(tarantool_tarantool_tuple_box_error_t *ptr);

void tarantool_tarantool_tuple_result_box_tuple_box_error_free(tarantool_tarantool_tuple_result_box_tuple_box_error_t *ptr);

void tarantool_tarantool_tuple_result_tuple_field_box_error_free(tarantool_tarantool_tuple_result_tuple_field_box_error_t *ptr);

void tarantool_tarantool_error_box_error_free(tarantool_tarantool_error_box_error_t *ptr);

void tarantool_tarantool_error_option_box_error_free(tarantool_tarantool_error_option_box_error_t *ptr);

void tarantool_tarantool_txn_box_error_free(tarantool_tarantool_txn_box_error_t *ptr);

void tarantool_tarantool_txn_result_void_box_error_free(tarantool_tarantool_txn_result_void_box_error_t *ptr);

void tarantool_tarantool_box_box_error_free(tarantool_tarantool_box_box_error_t *ptr);

void tarantool_tarantool_box_result_space_box_error_free(tarantool_tarantool_box_result_space_box_error_t *ptr);

void tarantool_tarantool_box_result_index_box_error_free(tarantool_tarantool_box_result_index_box_error_t *ptr);

void tarantool_tarantool_box_result_box_tuple_box_error_free(tarantool_tarantool_box_result_box_tuple_box_error_t *ptr);

void tarantool_tarantool_box_result_void_box_error_free(tarantool_tarantool_box_result_void_box_error_t *ptr);

void tarantool_tarantool_session_box_error_free(tarantool_tarantool_session_box_error_t *ptr);

void tarantool_tarantool_session_storage_free(tarantool_tarantool_session_storage_t *ptr);

void tarantool_tarantool_session_peer_free(tarantool_tarantool_session_peer_t *ptr);

void tarantool_tarantool_session_result_void_box_error_free(tarantool_tarantool_session_result_void_box_error_t *ptr);

void tarantool_tarantool_session_result_s64_box_error_free(tarantool_tarantool_session_result_s64_box_error_t *ptr);

void tarantool_tarantool_session_result_bool_box_error_free(tarantool_tarantool_session_result_bool_box_error_t *ptr);

void tarantool_tarantool_session_result_peer_box_error_free(tarantool_tarantool_session_result_peer_box_error_t *ptr);

void tarantool_tarantool_session_result_string_box_error_free(tarantool_tarantool_session_result_string_box_error_t *ptr);

void tarantool_tarantool_session_result_storage_box_error_free(tarantool_tarantool_session_result_storage_box_error_t *ptr);

void tarantool_tarantool_sequence_box_error_free(tarantool_tarantool_sequence_box_error_t *ptr);

void tarantool_tarantool_sequence_result_s64_box_error_free(tarantool_tarantool_sequence_result_s64_box_error_t *ptr);

void tarantool_tarantool_sequence_result_void_box_error_free(tarantool_tarantool_sequence_result_void_box_error_t *ptr);

void tarantool_tarantool_sequence_option_sequence_options_free(tarantool_tarantool_sequence_option_sequence_options_t *ptr);

void tarantool_tarantool_sequence_result_sequence_box_error_free(tarantool_tarantool_sequence_result_sequence_box_error_t *ptr);

void tarantool_tarantool_index_box_error_free(tarantool_tarantool_index_box_error_t *ptr);

void tarantool_tarantool_index_key_part_def_free(tarantool_tarantool_index_key_part_def_t *ptr);

void tarantool_tarantool_index_key_part_def_list_free(tarantool_tarantool_index_key_part_def_list_t *ptr);

void tarantool_tarantool_index_update_op_free(tarantool_tarantool_index_update_op_t *ptr);

void tarantool_tarantool_index_tuple_list_free(tarantool_tarantool_index_tuple_list_t *ptr);

void tarantool_tarantool_index_pairs_opts_free(tarantool_tarantool_index_pairs_opts_t *ptr);

void tarantool_tarantool_index_select_opts_free(tarantool_tarantool_index_select_opts_t *ptr);

void tarantool_tarantool_index_result_s64_box_error_free(tarantool_tarantool_index_result_s64_box_error_t *ptr);

void tarantool_tarantool_index_result_box_tuple_box_error_free(tarantool_tarantool_index_result_box_tuple_box_error_t *ptr);

void tarantool_tarantool_index_result_bool_box_error_free(tarantool_tarantool_index_result_bool_box_error_t *ptr);

void tarantool_tarantool_index_result_index_type_box_error_free(tarantool_tarantool_index_result_index_type_box_error_t *ptr);

void tarantool_tarantool_index_result_key_part_def_list_box_error_free(tarantool_tarantool_index_result_key_part_def_list_box_error_t *ptr);

void tarantool_tarantool_index_result_own_iterator_box_error_free(tarantool_tarantool_index_result_own_iterator_box_error_t *ptr);

void tarantool_list_box_tuple_free(tarantool_list_box_tuple_t *ptr);

void tarantool_tarantool_index_result_list_box_tuple_box_error_free(tarantool_tarantool_index_result_list_box_tuple_box_error_t *ptr);

void tarantool_tarantool_index_list_update_op_free(tarantool_tarantool_index_list_update_op_t *ptr);

void tarantool_tarantool_index_list_key_part_def_free(tarantool_tarantool_index_list_key_part_def_t *ptr);

void tarantool_tarantool_index_result_void_box_error_free(tarantool_tarantool_index_result_void_box_error_t *ptr);

void tarantool_tarantool_index_result_index_stat_box_error_free(tarantool_tarantool_index_result_index_stat_box_error_t *ptr);

// Transfers ownership of `s` into the string `ret`
void tarantool_string_set(tarantool_string_t *ret, const char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void tarantool_string_dup(tarantool_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void tarantool_string_free(tarantool_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
