name: Publish Tarantool WIT Component to GitHub Container Registry

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.10.15

      - name: Install wkg
        shell: bash
        run: |
          cargo binstall wkg

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.7.0

      - name: Get version from tag
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/mandesero/tarantool/tarantool
          tags: |
            type=semver,pattern={{version}}

      - name: Docker login to GHCR
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build WIT to Wasm
        shell: bash
        run: wkg wit build -o tarantool-tarantool.wasm

      - name: Publish to GitHub Container Registry
        id: publish
        uses: bytecodealliance/wkg-github-action@v5
        with:
          oci-reference-without-tag: ghcr.io/mandesero/tarantool/tarantool
          file: 'tarantool-tarantool.wasm'
          description: 'WIT definitions for Tarantool (WASM component)'
          source: 'https://github.com/mandesero/tarantool-wit'
          homepage: 'https://github.com/mandesero/tarantool-wit'
          version: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          licenses: 'BSD-2-Clause'

      - name: Sign the Wasm component
        run: |
          cosign sign --yes ghcr.io/mandesero/tarantool/tarantool@${{ steps.publish.outputs.digest }}
